### ISSUE TITLE
Is this library thread-safe?

### ISSUE THREAD

**Issue by moien007** [Washi1337/AsmResolver#101]
Hi,

I was wondering if this library is thread-safe or not? If not, is it achievable externally?

**Comment by Washi1337** [comment]
Models that are lazily initialized have a guarantee that accessing properties from different threads should work without problems. The initialization of these properties are either locked on using a `lock` statement, or `Interlocked.CompareExchange` is used just before assigning the new value.

That being said, there is always the possibility that I have missed something.

**Comment by moien007** [comment]
> Models that are lazily initialized have a guarantee that accessing properties from different threads should work without problems. The initialization of these properties are either locked on using a `lock` statement, or `Interlocked.CompareExchange` is used just before assigning the new value.

Great!

> That being said, there is always the possibility that I have missed something.

I'll open an issue if I encounter an error.
