### ISSUE TITLE
Making SearchDirectories array visible from interface level

### ISSUE THREAD

**Issue by TheProxyRE** [Washi1337/AsmResolver#106]
Currently IMetadataResolver interface does not contain SearchDirectories array so cast to
AssemblyResolverBase is required.

Instead of doing
```csharp
var resolver = (AssemblyResolverBase)module.MetadataResolver.AssemblyResolver;
resolver.SearchDirectories.Add(path);
```
it would be nice if we can accesses it directly from AssemblyResolver
```csharp
module.MetadataResolver.AssemblyResolver.SearchDirectories.Add(path);
```

**Comment by Washi1337** [comment]
Problem with this is that this change breaks modularity / SOLID. Some `IAssemblyResolver` implementations might not use search directories, or at least not directly (e.g. the assembly resolver in the workspaces branch doesn't directly use it).
