### ISSUE TITLE
What's the difference between AsmResolver and dnlib?

### ISSUE THREAD

**Issue by CreateAndInject** [Washi1337/AsmResolver#111]
I often use dnlib, today, I found this repository.
What's the difference between AsmResolver and dnlib?
Is there anything AsmResolver can do(or do better/easier) which dnlib can't?

**Comment by Charterino** [comment]
AsmResolver has a really good documentation, and some features dnlib lacks.

**Comment by Washi1337** [comment]
Disclaimer: I have _very limited_ experience dnlib myself. so I would not really be able to tell exactly what AsmResolver has what dnlib hasn't and vice versa. I have more experience with librareis such as Mono.Cecil, and can therefore only compare it to this library. However, as far as I know dnlib was based off of Cecil, some of the points might be applicable.

That being said: AsmResolver started out as an experimental project that has grown out to be a full Windows PE inspection library, that includes some quality of life improvements that focus on having more control over what happens under the hood. 

These include e.g.:
- It uses a more consistent naming convention (something I rather dislike about dnlib personally). 
- It is not one monolithic package, but rather split up in multiple packages that allow you to only include what you need in your project.
- It works in layers of abstraction. This allows for both high-level access that you might be used to in dnlib, as well as very low level access (editing PE headers, metadata streams etc.)
- A central place for documentation.

Some .NET specifics include:
- It has a built-in reference importing and member cloning mechanisms that aid in copying members from module to module.
- It allows for preserving metadata tokens, and allocating and assigning new metadata tokens to new members before saving a module to the disk.
- Fully static type memory layout calculation, allowing you to determine the size of a type and the offsets of fields within that type, taking struct layouts and alignments into account.
- Full strong name signature support.

**Comment by CreateAndInject** [comment]
https://github.com/Washi1337/AsmResolver/wiki/X86
I can't find someting mentioned in the wiki, such as `X86Disassembler`, why?

**Comment by Washi1337** [comment]
The wiki on GitHub is out of date and refers to an older version of AsmResolver. The newer version does not include a built-in x86 encoder and decoder. It would be best to use a library such as Iced instead.

**Comment by CreateAndInject** [comment]
I want to know whether AsmResolve has the same issue https://github.com/0xd4d/dnlib/issues/408 like dnlib.
I think `GenericParameterSignature` is the same thing like `GenericVar` and `GenericMVar`, but I found `GenericParameterSignature` doesn't store its owner, so I can't know which type/method the  `GenericParameterSignature` come from, and don't know its name(such as `T`, `TKey` rather than `!0`, `!!0`)

**Comment by Washi1337** [comment]
`GenericParameterSignature` indeed doesn't store the owner. The reason is that these signatures do not reference the original member that they belong to in the first place. If you want to get the `GenericParameter` that the signature refers to, you should resolve the method or type that this signature comes from, and look up the generic parameter with the help of the `GenericParameterSignature.Index` property.

Maybe also something to note. If you are looking for a way to easily replace all `!0`s and `!!0`s with their instantiations, there is a very easy way to substitute all `GenericParameterSignature`s in e.g. a `TypeSignature` or `MethodSignature` using the `InstantiateGenericTypes` method. This will return a copy of the type/method signature with all these parameters substituted with the arguments of the generic context that you provide.

Example:
```csharp
// Get generic instance method operand.
var someMethodSpec = (MethodSpecification) instruction.Operand;

// Define generic context.
var context = new GenericContext(null, someMethodSpec.Signature);

// Instantiate the method signature:
var originalSignature = someMethodSpec.Method.Signature;
var instantiatedSignature = originalSignature.InstantiateGenericTypes(context);
```

**Comment by CreateAndInject** [comment]
Thanks

**Comment by arash88** [comment]
Hi @Washi1337 ,
Sorry for opening this thread again, I thought it's better not to open another issue for this question:
**Can AsmResolver deal with heavily obfuscated assemblies with invalid metadata as dnlib does?**

**Comment by HoLLy-HaCKeR** [comment]
> 
> 
> Hi @Washi1337 ,
> Sorry for opening this thread again, I thought it's better not to open another issue for this question:
> 
> **Can AsmResolver deal with heavily obfuscated assemblies with invalid metadata and load them successfully as dnlib does?**

Yes, it's intended for that
