### ISSUE TITLE
NativeMethodBody how to use string ？

### ISSUE THREAD

**Issue by dmhai** [Washi1337/AsmResolver#114]
I did not find the  wiki about it.

how to use the string in the NativeMethodBody?

I want to do this with NativeMethod:

`

		public static int GetSum(int num1, int num2)
		{
			return num1 + num2;
		}

		public static string ConcatIntAndString(int num1, string str1)
		{
			return num1.ToString() + str1;
		}
		
		public static string ConcatString(string str1, string str2)
		{
			return "abc" + str1 + "def";
		}

`
can you write some demo？thanks。

**Comment by Washi1337** [comment]
Hi,

I am not too sure what you are asking. Could you elaborate please? Do you wish to add native method bodies to a module? 

AsmResolver does not come yet with rich support for native methods out of the box in high level mode (at least not on `master` or `development`). 

It is a planned feature though (#52): There is already some experimentation on the `feature/native-method-body`, not sure if you were talking about that `NativeMethodBody` class, but it is by no means finalized yet. 

Regards,

**Comment by dmhai** [comment]
Thanks for your answer。

yes，I am talking about [feature/native-method-body] branch。

You created a native  method in your test code and returned 1337.

I want to know how to  return a string。

**Comment by Washi1337** [comment]
I'd suggest you learn how x86 works with strings then. They usually work in terms of output buffers passed on as an argument, or allocating new strings using functions like `malloc` and returning a `char*`. It becomes substantially more involved if you want to return managed `System.String` objects in pure x86. This 

Also, be aware `feature/native-method-body` is a very outdated branch.
