### ISSUE TITLE
NuGet Package?

### ISSUE THREAD

**Issue by Abdullah2993** [Washi1337/AsmResolver#12]
can you please setup a nuget package?

**Comment by JerreS** [comment]
Here you go:

https://www.nuget.org/packages/AsmResolver

**Comment by silasary** [comment]
The nuget package is currently out of date.

You might want to consider configuring AppVeyor to automatically publish new builds.

**Comment by Washi1337** [comment]
Got it to work. Enjoy!

**Comment by silasary** [comment]
Awesome.  Thanks!
