### ISSUE TITLE
Adding A bool property for Methods if it hasbody or not

### ISSUE THREAD

**Issue by CursedLand** [Washi1337/AsmResolver#125]
:)

**Comment by Washi1337** [comment]
Note: For consistency with the `MethodBody` property, this property should be called `HasMethodBody`.

**Comment by CursedLand** [comment]
> 
> 
> Note: For consistency with the `MethodBody` property, this property should be called `HasMethodBody`.

;D

**Comment by Washi1337** [comment]
Implemented in 795a3e25fee5505f338fa68929b57870a69009ab. Will be on nuget in 4.4.0
