### ISSUE TITLE
[Thread-Safety] Exception thrown when accessing method body concurrently.

### ISSUE THREAD

**Issue by moien007** [Washi1337/AsmResolver#135]
The following code reproduces the problem:
```csharp
var asmDef = AssemblyDefinition.FromFile(typeof(AssemblyDefinition).Assembly.Location);
var allTypes = asmDef.Modules.SelectMany(x => x.GetAllTypes()).ToArray();
var allMethods = allTypes.SelectMany(x => x.Methods).ToArray();
Parallel.ForEach(allMethods, method =>
{
    if (!(method.HasMethodBody && method.IsIL))
        return;

    foreach (var instruction in method.CilMethodBody.Instructions)
    {
        GC.KeepAlive(instruction);
    }
});
```

The workaround is walking every method body in a single thread first, like the following:
```csharp
foreach (var method in allMethods)
{
    if (!(method.IsIL && method.HasMethodBody))
        continue;
                
    foreach (var instruction in method.CilMethodBody.Instructions)
    {
            GC.KeepAlive(instruction);
    }
}
```
And then going parallel.

My suggestion is to add an option to pre-load all lazy-loaded items.

**Comment by Washi1337** [comment]
Thanks a lot for the report and the very useful repro code! 

Preloading everything is not really a solution, but more of a mitigation that hides the true problem.

The issue seems to be a concurrency issue in `SerializedMetadataTable`. I pushed a potential fix to [issue/135](/Washi1337/AsmResolver/tree/issue/135). Can you verify that this indeed fixes your issue?

**Comment by moien007** [comment]
> Thanks a lot for the report and the very useful repro code!
> 
> Preloading everything is not really a solution, but more of a mitigation that hides the true problem.
> 
> The issue seems to be a concurrency issue in `SerializedMetadataTable`. I pushed a potential fix to [issue/135](/Washi1337/AsmResolver/tree/issue/135). Can you verify that this indeed fixes your issue?

Great job. No exceptions so far.

**Comment by Washi1337** [comment]
Perfect. Then this will be merged into development, and put into the next release on nuget.
