### ISSUE TITLE
I want to modify the icon in exe, don't know how to operate?

### ISSUE THREAD

**Issue by xmoer** [Washi1337/AsmResolver#14]
Can this tool be used to modify an icon in EXE or to modify the image resources in a DLL file?
I don't quite understand how to use it.

**Comment by Washi1337** [comment]
Hi,

The library supports adding, editing and removing native resources, as well as managed .NET resources. Assuming you have a variable `assembly` of type `WindowsAssembly`, the native resources can be accessed through the `assembly.RootResourceDirectory` property, and the raw .NET resources data can be accessed through the `assembly.NetDirectory.ResourcesManifest` property. Keep in mind these are closely following the structure of the PE, which might require you to have some knowledge of the inner workings of the resource directories.

If you are looking to edit .NET manifest resources though, the easiest way to inspect the resources is by locking the metadata through `var image = assembly.NetDirectory.MetadataHeader.LockMetadata()`, and use the `image.Assembly.Resources` property instead. 

It has to be noted though, that currently version 3.0 only ships with a .NET assembly builder. Effectively this means that there is only full support for assemblies that contain .NET metadata to be written to the hard-disk. If you desire to write native assemblies instead, you have to do a little more work yourself and create your own derivative of the `WindowsAssemblyBuilder` class. More native support is expected to be added in the not so far future. For that, pay close attention to updates to the `development` branch if you are interested.

I would like to add that if your intentions is to update native resources only, then this library is probably overkill for your use case. The goal of AsmResolver is to create, inspect and edit assemblies very thoroughly, including modifying actual code. Writing assemblies often completely reconstructs the entire PE, which may have unwanted side-effects.

Regards

**Comment by xmoer** [comment]
Thank you very much for your reply. This tool is so powerful.

Since there are no detailed wiki usage instructions, I need some time to study all the functions. I think it's a good idea to use this library to dynamically compile and generate installation packages.

**Comment by Washi1337** [comment]
Yes I am aware that there is no wiki or tutorial available yet besides the very small quick starters guide in the README.md. Will have to work on that too :)
