### ISSUE TITLE
Exception is thrown at beginning of disassembling

### ISSUE THREAD

**Issue by moien007** [Washi1337/AsmResolver#15]
Exception thrown:
`System.NotSupportedException: 'Unrecognized or unsupported addressing method.'` at line `while ((inst = disassembler.ReadNextInstruction()) != null)`

Program.cs:

        static void Main(string[] args)
        {
            var winAsm = WindowsAssembly.FromFile("testpe2.exe");
            var reader = winAsm.ReadingContext
                               .Reader
                               .CreateSubReader(winAsm.NtHeaders.OptionalHeader.BaseOfCode,
                                           (int)winAsm.NtHeaders.OptionalHeader.SizeOfCode);

            var disassembler = new X86Disassembler(reader);

            X86Instruction inst;
            while ((inst = disassembler.ReadNextInstruction()) != null)
            {
                Console.WriteLine(inst);
            }

            Console.ReadKey();
        }

What's wrong?

**Comment by Washi1337** [comment]
Hey,

If the PE is not copyrighted, is it possible for you to share it with me in some way or another? This seems like a bug in the disassembler. If it is not possible, could you perhaps send an excerpt of the bytes that you are trying to disassemble?

Also, keep in mind X86Disassembler.ReadNextInstruction does not return `null` when it reaches the end of the stream. Instead, you should be checking `reader.Position` together with `reader.StartPosition` and `reader.Length` to determine whether the reader has read all the bytes.

Regards,

**Comment by moien007** [comment]
> If the PE is not copyrighted, is it possible for you to share it with me in some way or another? This seems like a bug in the disassembler. If it is not possible, could you perhaps send an excerpt of the bytes that you are trying to disassemble?

It isn't copyrighted since it's just a simple VC++ (VS2017) compiled program (written by me).
```
int main(int argc, char *argv[])
{
	return argc;
}
```
Yep, very simple :D. Here's the binary file: https://ufile.io/76x4o. <br/> <br/>

> Also, keep in mind `X86Disassembler.ReadNextInstruction` does not return `null` when it reaches the end of the stream, but rather throws an exception when it cannot read any more bytes. Instead, you should be checking `reader.Position` together with `reader.StartPosition` and `reader.Length` to determine whether the reader has read all the bytes.

It'll be nice if you make it return null when reader reaches the end of stream or add a property to reader that indicates the end of stream.

Regards.

**Comment by Washi1337** [comment]
My apologies for the late reply. 

First things first. You are misusing the `CreateSubReader` function. `CreateSubReader` accepts a file offset and a length, but `BaseOfCode` is an RVA. To translate the RVA to a file offset you can use `winAsm.RvaToFileOffset(offset)`.

However, this does not completely solve the issue. The disassembler still has a few limitations regarding some operands. You will find it crashing eventually on some instructions that deal with e.g. segment registers. Will have to update that :)

> It'll be nice if you make it return null when reader reaches the end of stream or add a property to reader that indicates the end of stream.

I will not change the behaviour of the disassembler for various reasons. Reading past the end of the stream is an illegal operation, an exception seems more fitting here, and for backwards compatibility. A typical loop for a full linear sweep disassembly is:

```csharp
var reader = winAsm.ReadingContext
    .Reader
    .CreateSubReader(
        winAsm.RvaToFileOffset(winAsm.NtHeaders.OptionalHeader.BaseOfCode),
        (int)winAsm.NtHeaders.OptionalHeader.SizeOfCode);

var disassembler = new X86Disassembler(reader);
while (reader.Position < reader.StartPosition + reader.Length)
{
    var instruction = disassembler.ReadNextInstruction();
    Console.WriteLine(instruction);
}
```

**Comment by moien007** [comment]
Thanks for the guidance,
