### ISSUE TITLE
Provide .NET Standard support?

### ISSUE THREAD

**Issue by 766F6964** [Washi1337/AsmResolver#16]
Will there ever be [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) support? 
This would make cross platform development a lot easier.

**Comment by Washi1337** [comment]
Hi,

Was planning on doing this some day anyway. Created a branch for it called `netstandard`. Keep in mind that some tests still fail because of some hardcoded references to mscorlib.
