### ISSUE TITLE
When Getting ThisParameter.ParameterType from Method Signature and its an Corlib signature it never converted to corlibtypesig

### ISSUE THREAD

**Issue by CursedLand** [Washi1337/AsmResolver#160]
When using `SomeMethod.Parameters.ThisParameter.ParameterType` and importing it it and it was CorLibSignature never converted to CorlibType

**Comment by Washi1337** [comment]
Note: this only happens for importing `TypeDefinition`s as `TypeSignature`s. For `TypeReference`s there already is a check for this.

**Comment by Washi1337** [comment]
Implemented in #162. Will be present in 4.6.0
