### ISSUE TITLE
FnPtr TypeSignature support

### ISSUE THREAD

**Issue by JPaja** [Washi1337/AsmResolver#167]
## Describe the bug
AsmResolver fails to parse TypeSignature that contains FnPtr signature

## To Reproduce
Download Silk.NET.OpenGL.dll from nuget 
https://www.nuget.org/packages/Silk.NET.OpenGL/
Tested with version 2.3.0

```csharp
var asm = AssemblyDefinition.FromFile("Silk.NET.OpenGL.dll");
asm.Write("Silk.NET.OpenGL.dll")
```

Faulty signature is signature (0x1100000A) of local variable from method `MultiDrawArraysIndirectCount` (0x06000039)

**Comment by Washi1337** [comment]
Implemented in e3343cc64efc642785b0470144d14ee02208ebdb
