### ISSUE TITLE
Parse multi file and other types of manifest resources

### ISSUE THREAD

**Issue by oSumAtrIX** [Washi1337/AsmResolver#169]
## Problem Description
It is not possible to parse a multi file resource to its resource elements which makes it not possible to read individual resources.

## Proposal
Implement a way to read and parse multi file resources  in order to read individual resource elements inside the manifest resource.

## Additional context
AsmResolver currently only reading manifest resources;
![Missing reader in AsmResolver](https://i.imgur.com/ARdW330.png)

Dnlib reading manifest resources and parsing it to a multi file resource;
![Existing reader in Dnlib](https://i.imgur.com/ub9Id4w.png)

**Comment by Washi1337** [comment]
Just to clarify, this is regarding files embedded into a single `.resources` file correct?

**Comment by oSumAtrIX** [comment]
Yes, you can create a single `.resource` file and embedd multiple files in it. There are other types of manifest resources as well

**Comment by Washi1337** [comment]
Official specification / documentation on the `.resources` file format seems kind of sparse, which means we might have to resort to the source code provided by the reference sources or CoreCLR. See [RuntimeResourceSet.cs](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Resources/RuntimeResourceSet.cs#L17).

After some research, reusing the default `ResourceManager`, `ResourceReader` and `ResourceSet` classes is out of the question. `.resources` files seem to support storing values of custom types. These types are loaded using `System.Reflection` which can lead to code execution upon loading the `.resources` file. We therefore must resort to a home-brew implementation.

One challenge is that in the header of the `.resources` file, two types are referenced. The first type is a type that implements `IResourceReader`, and the second type is a type inheriting from `ResourceSet`. While the CLR and CoreCLR only seem to provide one default implementation for both of these classes (`ResourceReader` and `RuntimeResourceSet`), and in practice only these two are used pretty much +90% of all "normal" applications, it is _technically_ possible that a sample references a different `IResourceReader` and/or `ResourceSet`, which is then instantiated dynamically (see e.g. [ManifestBasedResourceGroveler.cs](https://github.com/dotnet/runtime/blob/9d771a26f058a9fa4a49850d4778bbab7aa79a22/src/libraries/System.Private.CoreLib/src/System/Resources/ManifestBasedResourceGroveler.cs#L252)). This affects the actual format used in the `.resources` file, making this a bit of a complicated task to do this fully statically.

We obviously cannot do this as this too would require `System.Reflection`, which should be avoided at all costs. However, to still support this in AsmResolver, we might need to make our own version of `IResourceReader`, and allow for custom implementations to be provided to the actual parsers.
