### ISSUE TITLE
Resources Duplicated

### ISSUE THREAD

**Issue by gferber** [Washi1337/AsmResolver#17]
I have an assembly with two Resources files embedded, and after processing the assembly with AsmResolver, it ends up copying the contents of the first resources file instead of using the contents of the second resources file.  The emitted assembly still shows the two resources files, and they have the correct names, the contents are just wrong.

All I'm using AsmResolver to do is change the assembly version and the version of certain referenced assemblies.  Not touching the Resources section at all.

**Comment by Washi1337** [comment]
Hi, 

Thanks for the report. Are we talking about .NET resources or native resources?
If .NET, this has been fixed in the development branch.

Regards,

**Comment by gferber** [comment]
.NET, and I'm happy to go grab the dev branch.
