### ISSUE TITLE
Reconsider CilRawMethodBody design to use readable segment objects / struct readers

### ISSUE THREAD

**Issue by Washi1337** [Washi1337/AsmResolver#171]
## Problem Description
Upon reading a managed PE, the raw CIL code is read pre-emptively, and stored in the `Code` property of a `CilRawMethodBody` instance. For large input binaries with lots of CIL method bodies,  this results in lots of arrays being allocated that are not always used.

## Proposal
Reconsider the design of `CilRawMethodBody` to avoid the allocations of the (almost) useless byte arrays. We can do this by replacing the `Code` property with a struct reader that is positioned at the start of the raw code stream, and has a length equal to the length of the code stream.

## Alternatives
We can also perhaps slice `IDataSource` instances instead, and delay the creation of actual reader structs.

## Additional context
N/A

**Comment by oSumAtrIX** [comment]
[Lazy initialization](https://docs.microsoft.com/en-US/dotnet/api/system.lazy-1?view=net-5.0)  could be used in this case

**Comment by Washi1337** [comment]
Lazy init is not going to avoid the actual allocation of the large byte array, which is what this issue is proposing :)

**Comment by Washi1337** [comment]
[Initial testing](/Washi1337/AsmResolver/tree/feature/large-method-bodies-bench) shows that while this is generally a good idea, it does not seem to impact memory consumption _that_ much as expected. 

Using a method that contains 7MB worth of instructions in a single method decreases memory consumption by about 7MB, but this is "only" around 2.6% of the total consumption that is used (most likely because it still allocates lots of small `CilInstruction` objects on the heap). 

Before:
|                                      Method |      Gen 0 |      Gen 1 |     Gen 2 |   Allocated |
|-------------------------------------------- |-----------:|-----------:|----------:|------------:|
|      HelloWorldPumped_ModuleDefinition_Read |    11.7188 |          - |         - |    48.59 KB |
| HelloWorldPumped_ModuleDefinition_ReadWrite | 24000.0000 | 10000.0000 | 3000.0000 | 273293.3 KB |

After changing `byte[]` to `IReadableSegment`:
|                                      Method |      Gen 0 |      Gen 1 |     Gen 2 |   Allocated |
|-------------------------------------------- |-----------:|-----------:|----------:|------------:|
|      HelloWorldPumped_ModuleDefinition_Read |    11.7188 |          - |         - |     48.6 KB |
| HelloWorldPumped_ModuleDefinition_ReadWrite | 24000.0000 | 10000.0000 | 3000.0000 | 266125.3 KB |

**Comment by Washi1337** [comment]
Test in the above might not be the best representation since it also measures the memory allocated by rebuilding the binary.

Further testing with the same pumped hello world application, but this time by force-loading all lazy variables + using memory mapped IO enabled, reveals significant memory consumption reduction. From 250MB to 220MB (-18%) and even as low as 160MB (-36%) after GC (possibly because the method body copies are not retained in memory after the method body is read in its entirety).

![dotmemory](https://user-images.githubusercontent.com/3613449/119345345-0b44ab80-bc99-11eb-816d-8deee850d2db.png)
