### ISSUE TITLE
Metadata.Rva == 0?

### ISSUE THREAD

**Issue by evandrix** [Washi1337/AsmResolver#194]
Metadata RVA should be 0x2068, not 0x00?

input file - Farm.dll 
[Farm.dll.zip](https://github.com/Washi1337/AsmResolver/files/6948473/Farm.dll.zip)

```
AsmResolver.PE.IPEImage peImgNet = AsmResolver.PE.PEImage.FromFile("Farm.dll");
AsmResolver.PE.DotNet.IDotNetDirectory dirNet = peImgNet.DotNetDirectory;
using (var stream = File.Create("dotNet-Dir.bin"))
{
  AsmResolver.IO.IBinaryStreamWriter wrtr = new AsmResolver.IO.BinaryStreamWriter(stream);
  dirNet.Write(wrtr);
}
```

```
0000000: 4800 0000 0200 0500 0000 0000 fc04 0000  H...............
0000010: 0900 0000 0000 0000 0000 0000 0000 0000  ................
0000020: 6425 0000 0002 0000 0000 0000 0000 0000  d%..............
0000030: 0000 0000 0000 0000 0000 0000 0000 0000  ................
0000040: 0000 0000 0000 0000                      ........
```

010 Editor
![screenshot 0](https://user-images.githubusercontent.com/169669/128584900-992462ce-00d9-494d-b396-1ce6604705c6.png)

CFF Explorer
![screenshot 1](https://user-images.githubusercontent.com/169669/128584903-4c44b58d-8b16-452e-992f-4e66a65fae04.png)

**Comment by Washi1337** [comment]
Thanks for catching this bug. This should be fixed on the development branch and will be part of 4.7.0 :)

**Comment by evandrix** [comment]
meanwhile, i've already implemented a hack :P

```
AsmResolver.PE.IPEImage peImgNet = AsmResolver.PE.PEImage.FromFile(peImg);
AsmResolver.PE.DotNet.SerializedDotNetDirectory dirNetSerial = (AsmResolver.PE.DotNet.SerializedDotNetDirectory) peImgNet.DotNetDirectory;
AsmResolver.PE.File.Headers.DataDirectory dirMd = dirNetSerial.GetFieldValue<AsmResolver.PE.File.Headers.DataDirectory>("_metadataDirectory");
uint dirMdAddr = dirMd.VirtualAddress;
ulong dirMdOffset = peImg.RvaToFileOffset(dirMdAddr);

```

**Comment by evandrix** [comment]
Not sure if you are able to add TypeRefHash (TRH) https://www.gdatasoftware.com/blog/2020/06/36164-introducing-the-typerefhash-trh as part of 4.7.0?

PeNet https://github.com/secana/PeNet has such a feature already

**Comment by Washi1337** [comment]
Would be nice if you could make a separate issue for this, as this helps me keep track of all the feature requests and bug reports, and provide the right attributions in the change logs.
