### ISSUE TITLE
TypeRefHash (TRH)

### ISSUE THREAD

**Issue by evandrix** [Washi1337/AsmResolver#195]
## Problem Description
We introduce the TypeRefHash (TRH) which is an alternative to the ImpHash that does not work with .NET binaries. Our evaluation shows that it can effectively be used to identify .NET malware families.

The ImpHash was introduced in 2014 by FireEye [1]. It has since been used by many malware analysts and implemented in tools like VirusTotal to identify similar malware samples by their imports. In theory, if programs use the same imports, they use similar source code. 

.NET samples usually only import mscoree.dll, such that there is only a handful of different ImpHashes for all .NET binaries. Therefore, the ImpHash cannot be used here. This motivated us to find an alternative, the TypeRefHash (TRH). To show the imported DLLs, functions and the TypeRef table, we used the online tool penet.io.

## Proposal
https://www.gdatasoftware.com/blog/2020/06/36164-introducing-the-typerefhash-trh
_To calculate the TRH we extract the TypeRef table and resolve the indices to the corresponding strings._

1. Order the entries by TypeNamespace and then by TypeName. 
2. Concatenate the TypeNamespaces and TypeNames with a dash. In case that the namespace is empty, the concatenated string starts with the dash. 
3. Join all strings with commas and calculate the SHA256 hashsum of the resulting UTF8 byte-string.

https://github.com/GDATASoftwareAG/TypeRefHasher

## Alternatives
- PeNet Web https://penet.azureedge.net
- PeNet https://github.com/secana/PeNet

## Additional context
- https://raw.githubusercontent.com/secana/PeNet/master/src/PeNet/Header/Net/TypeRefHash.cs
- https://bbs.pediy.com/thread-263384.htm

**Comment by evandrix** [comment]
```
AsmResolver.PE.DotNet.Metadata.Tables.MetadataTable<AsmResolver.PE.DotNet.Metadata.Tables.Rows.TypeReferenceRow> typeRefTbl = tblStream.GetTable<AsmResolver.PE.DotNet.Metadata.Tables.Rows.TypeReferenceRow>();
IList<String> typeRefs = typeRefTbl
  .OrderBy(row=>strStream.GetStringByIndex(row.Namespace))
  .ThenBy(row=>strStream.GetStringByIndex(row.Name))
  .Select(row=>String.Join("-",strStream.GetStringByIndex(row.Namespace),strStream.GetStringByIndex(row.Name)))
  .ToList();
String typeRefsStr = String.Join(",",typeRefs);
SHA256 sha256 = SHA256.Create();
byte[] hashSha256 = sha256.ComputeHash(System.Text.Encoding.UTF8.GetBytes(typeRefsStr));
System.Console.WriteLine("sha256: "+BitConverter.ToString(hashSha256).Replace("-","").ToLower());
```

**Comment by Washi1337** [comment]
I am wondering about certain design questions regarding this new feature. In particular, where should this extension live in the codebase, and how it should be invoked by the end-user?

Below are a couple of suggestions I was thinking of:

1. Add it as an extension to the `TablesStream`:
    ```csharp
    var stream = peImage.DotNetDirectory.Metadata.GetStream<TablesStream>();
    byte[] hash = stream.GetTypeReferenceHash();
    ```

2. Add it as an extension to any instance of `MetadataTable<TypeReferenceRow>`:
    ```csharp
    var table = peImage.DotNetDirectory.Metadata
       .GetStream<TablesStream>()
       .GetTable<TypeReferenceRow>();
    
    byte[] hash = table.GetTypeReferenceHash();
    ```

3. Don't use an extension at all, and just leave it as a separate static class `TypeReferenceHash`:
    ```csharp
    var table = peImage.DotNetDirectory.Metadata
       .GetStream<TablesStream>()
       .GetTable<TypeReferenceRow>();

    byte[] hash = TypeReferenceHash.FromTable(table);
    ```

I am not too sure yet what would be the most intuitive. Maybe you have some idea about this?

As a side note: given that this is not that difficult to implement, we might as well just add an implementation for the "normal' import hash as well.

**Comment by evandrix** [comment]
as per my implementation provided, i'm inclined to go with your proposal 2., since the TypeRefHash is computed over TypeReferenceRow's, although your last suggestion to extend IPEImage directly, would be the most accessible to a beginner.
