### ISSUE TITLE
Changing access modifiers causes problematic behavior

### ISSUE THREAD

**Issue by vikigenius** [Washi1337/AsmResolver#206]
## Describe the bug
Changing access modifiers messes with Explicit Interface implementations

## To Reproduce
Here is an example assembly

Base Class Interface
```C#
using System;

namespace AccessTest
{
	// Token: 0x02000003 RID: 3
	public interface MyBase
	{
		// Token: 0x17000001 RID: 1
		// (get) Token: 0x06000002 RID: 2
		// (set) Token: 0x06000003 RID: 3
		string name { get; set; }
	}
}
```

Here is the derived class

```C#
using System;

namespace AccessTest
{
	// Token: 0x02000004 RID: 4
	public class MyDerived : MyBase
	{
		// Token: 0x17000002 RID: 2
		// (get) Token: 0x06000004 RID: 4 RVA: 0x00002059 File Offset: 0x00000259
		// (set) Token: 0x06000005 RID: 5 RVA: 0x00002061 File Offset: 0x00000261
		string MyBase.name
		{
			get
			{
				return this.name;
			}
			set
			{
				this.name = value;
			}
		}

		// Token: 0x04000001 RID: 1
		public string name;

		// Token: 0x04000002 RID: 2
		private string m_privateName;
	}
}
```

I am trying to convert all the private fields and methods of the assembly to public like this:

```C#
public static class AssemblyPatcher
{
    public static void Patch(ModuleDefinition module)
    {
        foreach (var type in module.GetAllTypes())
        {
            if (type.Name != "MyDerived")
            {
                continue;
            }
            
            if (type.IsNested)
                type.IsNestedPublic = true;
            else
                type.IsPublic = true;

            foreach (var method in type.Methods)
            {
                method.IsPublic = true;
            }

            foreach (var field in type.Fields)
            {
                field.IsPublic = true;
            }
            
        }
    }
}
```

The output assembly produces the following snippet:

```C#
using System;

namespace AccessTest
{
	// Token: 0x02000004 RID: 4
	public class MyDerived : MyBase
	{
		// Token: 0x17000002 RID: 2
		// (get) Token: 0x06000004 RID: 4 RVA: 0x00002059 File Offset: 0x00000259
		// (set) Token: 0x06000005 RID: 5 RVA: 0x00002061 File Offset: 0x00000261
		public string name
		{
			get
			{
				return this.name;
			}
			set
			{
				this.name = value;
			}
		}

		// Token: 0x04000001 RID: 1
		public string name;

		// Token: 0x04000002 RID: 2
		public string m_privateName;
	}
}
```
This is problematic because it converts the explicit interface implementation to a conflicting property implementation for name.

## Expected behavior
AsmResolver should keep the explicit interface implementation as is

## Platform
 - OS: Windows 10
 - AsmResolver Version: 4.6.0

**Comment by Washi1337** [comment]
This is not a bug, but an artifact of the decompiler that you are using. It is a direct consequence of when you mark explicit implementations public.

You can see this for yourself by changing the access modifier of the getter method in e.g. dnSpy, and see how the decompilation changes from `string MyBase.name { get; set; }` to  `public string name { get; private set; }`. Furthermore, the `MethodImpl`s rows indicating the explicit interface implementations are still there (look in the `Overrides` tab of the getter method).

As for conflicts, the CLR allows for names to be the same when the type of member is different. For example, if a field is called `name` and in the same class a method or property is called `name` as well, it has no effect. This is because in CIL (the underlying language that C# gets compiled to) you will be referencing the field using a specific field definition metadata token, rather than by its name.

```
ldarg.0
ldfld 0x04000001 // (string MyDerived::name)
```

Note that this is different from C#, where the same names are **not** allowed.

**Comment by vikigenius** [comment]
@Washi1337 thanks for the explanation. The reason I reported it as a bug because when I tried to reference the publicized assembly in Jetbrains Rider. The intellisense shows an ambiguous reference error.

But looks like you are right, actually building the project does build without errors. But the intellisense shows it as an error. Still, is there an easy way that I can exclude making the explicit implementations as non public?

**Comment by Washi1337** [comment]
Yes. `TypeDefinition` exposes a property called `MethodImplementations`, which holds all explicit implementations done by the type. You can use it to exclude the methods that are explicitly implementing an interface method.

Something like the following could work:
```csharp
foreach (var method in type.Methods)
{
    if (type.MethodImplementations.Any(i => i.Body == method))
        continue;
    method.IsPublic = true;
}
```

**Comment by vikigenius** [comment]
Thanks that's very helpful. I actually opened a bug report on Jetbrains Rider, because the Visual Studio decompiler does not seem to produce this error. It actually still shows it as an explicit implementation and the Intellisense does not report it as an error either.

Meanwhile I will use your trick to publicize my assemblies.

**Comment by Washi1337** [comment]
Visual Studio uses ILSpy as decompiler back-end, whereas JetBrains uses dotPeek. I guess that explains the difference that you see in the two outputs. For what it's worth, both outputs are perhaps not really incorrect, given that in C# there is not really a concept for explicitly implemented methods that are also marked public.
