### ISSUE TITLE
System.InvalidOperationException on 64bit assembly

### ISSUE THREAD

**Issue by shadowua** [Washi1337/AsmResolver#21]
I was testing OldRod on some dummies and found out that it cannot reassemble 64bit net files. 

Here is log:

```
// ...
21:24:16.586 [Main]: Executing Clean up stage...
21:24:16.587 [Main]: Commiting changes to metadata streams...
21:24:16.790 [Main]: Not removing koi stream as some exports were ignored.
21:24:16.791 [Main]: Reassembling file...
21:24:16.812 [TUI]: Something went wrong! Try the latest version or report a bug
 at the repository.
21:24:16.819 [TUI]: System.InvalidOperationException: Sequence contains no matching element
// ...
```

It seems that is related to the fact that AsmResolver cannot find and properly write import directory to assembly as there is none in 64bit file. I have attached the file that I am working with.
[WindowsFormsApplication4.zip](https://github.com/Washi1337/OldRod/files/3725897/WindowsFormsApplication4.zip)

**Comment by Washi1337** [comment]
V3 now no longer includes the bootstrapper, import directory and relocations directory for 64-bit .NET assemblies. This should fix this issue.
