### ISSUE TITLE
How to update some text content in StringTable?

### ISSUE THREAD

**Issue by laomms** [Washi1337/AsmResolver#219]
For example, this file: C:\Windows\Branding\Basebrd\en-US\basebrd.dll.mui, I want change the 251 resourceId content to "Preview-Version":

![pic](https://user-images.githubusercontent.com/23111726/142745048-93242fc9-387f-475d-b4ce-5cad670cc9dc.png)

**Comment by Washi1337** [comment]
Hi, unfortunately `RT_STRING` resources do not have rich support yet in AsmResolver. As indicated in #66, high-level representations of win32 resources is still very much a work in progress.

That being said, it is possible to edit a string manually. `RT_STRING` entries are almost directly reflected in the raw win32 resource directory structure, as can be seen in tools like CFF Explorer:

![cff](https://user-images.githubusercontent.com/3613449/142759307-c1e7af57-13b3-4c44-908d-41922c5d692d.png)

AsmResolver follows this structure as well. So what you can do, is follow this path in the win32 resource directory down to the data entry of the string block you want to edit, manually swap the contents, then update the PE file with anew `.rsrc` section.

<details>
<summary>Example code</summary>

```csharp
// Read raw PE file. 
var file = PEFile.FromFile("basebrd.dll.mui");

// Open as image.
var image = PEImage.FromFile(file);

// Look up string entry.
var stringTables = (IResourceDirectory) image.Resources.Entries.First(e => e.Id == (int) ResourceType.String);
var stringEntry = (IResourceDirectory) stringTables.Entries.First(e => e.Id == 251); // ID
var dataEntry = (IResourceData) stringEntry.Entries.First(e => e.Id == 1033); // Lang ID

// Build up new string contents
const string newString = " Preview-Version";
using var stream = new MemoryStream();
var writer = new BinaryStreamWriter(stream);
writer.WriteUInt16((ushort) newString.Length);
writer.WriteBytes(Encoding.Unicode.GetBytes(newString));
writer.Align(4);

// Swap old data with new data (NOTE: in this example it erases any other string in this block as well, so in your 
// implementation you might want to change this slightly).
dataEntry.Contents = new DataSegment(stream.ToArray());

// Swap contents of original .rsrc section with new resource directory buffer.
var rsrc = file.Sections.First(s => s.Name == ".rsrc");
var newContents = new ResourceDirectoryBuffer();
newContents.AddDirectory(image.Resources);
rsrc.Contents = newContents;

// Update data directory in optional header.
file.AlignSections();
file.OptionalHeader.DataDirectories[(int) DataDirectoryIndex.ResourceDirectory] =
    new DataDirectory(newContents.DirectoryTable.Rva, newContents.DirectoryTable.GetPhysicalSize());

// Save.
file.Write("basebrd.dll.mui.patched");
```
</details>

**Comment by laomms** [comment]
Thanks @Washi1337, it's a great library.

I've seen a similar project(https://github.com/kohoutech/Resourcery) where able to list detailed resource information. Unfortunately it doesn't have to save the modified resource function.

**Comment by Washi1337** [comment]
I am not familiar with Resourcery, but it seems like it is a program with the sole purpose of viewing/editing resources of a PE file. 

Both projects probably have pros and cons and it depends on what you need on whether you want to go with AsmResolver or a project such as Resourcery. The rich feature set of AsmResolver may make "simple" tasks (such as editing a single string entry) a bit more complicated than just calling a single function as other libraries might provide. On the other hand, the goal of AsmResolver is not to be just a resources editor, but an entire PE editor, giving you more freedom in what you can do and cannot do.

**Comment by laomms** [comment]
Thanks very much. now I can search for arrays and replace them.

`var stringTables = (IResourceDirectory) image.Resources.Entries.First(e => e.Id == (int) ResourceType.String);
var stringEntry = (IResourceDirectory) stringTables.Entries.First(e => e.Id == 251); // ID
var dataEntry = (IResourceData) stringEntry.Entries.First(e => e.Id == 1033); // Lang ID
byte[] content = ((AsmResolver.DataSegment)dataEntry.Contents).Data;
Console.WriteLine (Encoding.Unicode.GetString(content));
`

**Comment by Washi1337** [comment]
Nice,  does that mean your issue has been resolved ?

**Comment by laomms** [comment]
yes, thank you verymuch!

**Comment by laomms** [comment]
Libraries are perfect if they have features like :   UpdateStringTable(GroupID,LangID,ResourceID,NewString ), so I can use only UpdateStringTable(251,1033,4001,"Preview-Version") ,just expect. :smile:
