### ISSUE TITLE
Retrieving Metadata token from a given string

### ISSUE THREAD

**Issue by ribthegreat99OrN0P** [Washi1337/AsmResolver#227]
Hello, i would like to propose a feature request.

I believe it will be very useful and interesting for many people who use AsmResolver (not just me) for a feature that will be able to retrieve the metadatatoken of a string given the operand (the string) and through the existing 'UserStringsStream'.

**Comment by Washi1337** [comment]
Note: we can probably extend this idea by adding methods to `StringsStream` and `GuidStream` that are analogous to the one presented here for `UserStringsStream`.
