### ISSUE TITLE
Potential Performance Hotspot

### ISSUE THREAD

**Issue by ds5678** [Washi1337/AsmResolver#232]
## Describe the bug
For writing my generated assembly, setting the `FileStream` position accounts for 66.8% of the time executing `AssemblyDefinition.Write`.

## Screenshots
![Screenshot 2021-12-19 192408](https://user-images.githubusercontent.com/49847914/146696394-1deadd98-4a93-42de-ba00-52b93124eac7.png)

## Platform
 - OS: Windows 10
 - AsmResolver Version: 4.7.1

**Additional context**
Profiled with tracing on JetBrains Rider 2021.3.1

**Comment by Washi1337** [comment]
Would it be possible to get a binary for which this is the case? On my machine I cannot seem to reproduce these types of percentages on `set_Position` calls. I tried saving `AsmResolver.DotNet`, as well as writing `System.Private.CoreLib`.

**Comment by Washi1337** [comment]
Also for consistency, we might as well want to add the same xmldocs to the `CilCode` enum.

**Comment by ds5678** [comment]
Here is my project: https://github.com/ds5678/AssemblyDumper/tree/SwitchToAsmResolver

Running it on any json file in this folder produces the issue: https://github.com/ds5678/TypeTreeDumps/tree/main/InfoJson

**Comment by Washi1337** [comment]
Tried on both Linux and Windows 11 x64, and still see a hotspot graph similar to the one below:

![x](https://user-images.githubusercontent.com/3613449/146968282-b40fa4fe-4e3c-4e33-8d36-f1d9ae114087.png)

This was tested with both nuget version 4.7.1, as well as the source available on `master` (which should be in sync with nuget's latest version). Target application was compiled for .NET 6.0, and I tried running it through [this json file](https://github.com/ds5678/TypeTreeDumps/blob/main/InfoJson/2017.1.0f3.json).

As can be seen from the screenshot, the `set_Position` calls made by the `SegmentBuilder` class only account for a very small fraction of all the processing time for me. Compared to `ToPEImage`, which almost takes all time, which is expected.

Perhaps it is hardware specific? Are you writing to a HDD or an SSD?

**Comment by ds5678** [comment]
HDD

**Comment by ds5678** [comment]
I going to try `AsmResolver.DotNet` and `System.Private.CoreLib` like you did.

**Comment by Washi1337** [comment]
Is it an old HDD? I am writing to a HDD now as well and still see similar results.

Perhaps, to reduce the amount of `set_Position` calls, you could perhaps try hotpatching the code at [BinaryStreamWriter.cs:22](https://github.com/Washi1337/AsmResolver/blob/master/src/AsmResolver/IO/BinaryStreamWriter.cs#L22] to something in the lines of :

```csharp
/// <inheritdoc />
public ulong Offset
{
    get => (uint) _stream.Position;
    set
    {
        if (_stream.Position != (long) value)
            _stream.Position = (long) value;
    }
}
```

Maybe the underlying `SetFilePointer` calls are expensive.

**Comment by ds5678** [comment]
My hard drive is about a year old. I have:
```
Seagate BarraCuda 2TB Internal Hard Drive HDD - 3.5 Inch SATA 6Gb/s 7200 RPM 256MB Cache 3.5-Inch
```
I used some simple code for testing:
```cs
public static void Main(string[] args)
{
	var assembly = AssemblyDefinition.FromFile(@"pathToAssembly");
	assembly.Write("output.dll");
}
```
I tried `AsmResolver.DotNet`. It was inline with your experience:
![asmresolver_write](https://user-images.githubusercontent.com/49847914/146973081-018adcd6-aaeb-4412-9987-d0950f298fca.png)

However, `System.Private.CoreLib` was worse than my initial experience:
![systemprivatecorlib_write](https://user-images.githubusercontent.com/49847914/146973182-9cec90ff-6d7c-4908-ac35-64e544f7f4ee.png)

These were done with the `4.7.1` nuget package. I'm going to try your hotpatch now.

**Comment by ds5678** [comment]
Actually, I figured out the problem. For some reason, this is way less efficient when overwriting an existing assembly. 

Here is `AsmResolver.DotNet` when overwriting using the nuget package:
![asmresolver_overwrite](https://user-images.githubusercontent.com/49847914/146975142-e805b498-69a6-4236-b76b-a78e2907b864.png)

**Comment by ds5678** [comment]
Your offset patch does improve performance slightly, but the `set_Position` calls under `BinaryStreamWriter.set_offset` are separate from the thousands of `set_Position` calls under `SegmentBuilder.Write`.

**Comment by Washi1337** [comment]
It's still difficult to get a consistent test for me. 

I have another suggestion however that you could perhaps try on your machine and see if it improves anything. Change the implementation of [SegmentBuilder.Write](https://github.com/Washi1337/AsmResolver/blob/master/src/AsmResolver/SegmentBuilder.cs#L92) with the following:

```csharp
/// <inheritdoc />
public void Write(IBinaryStreamWriter writer)
{
    for (int i = 0; i < _items.Count; i++)
    {
        var current = _items[i];
        writer.Align(current.Alignment);
        current.Segment.Write(writer);
    }
}
```

This avoids the `set_Position` all together and just aligns with zeroes.

**Comment by ds5678** [comment]
That combined with your other patch worked marvelously.
![Screenshot 2021-12-24 025424](https://user-images.githubusercontent.com/49847914/147331794-191ab272-a538-4e2f-b05a-cf893f3d7f6e.png)

**Comment by Washi1337** [comment]
Perfect, I'll make sure this will be in 4.8 then. Does that mean everything got resolved regarding this issue?

**Comment by ds5678** [comment]
Yeah it's wonderful. I can't notice a difference between overwriting and creating a new file
