### ISSUE TITLE
Create `ModuleDefinition.FromModule` factory method

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [Washi1337/AsmResolver#233]
## Problem Description
I was porting code from dnlib where I instantiate a `ModuleDef` from a `System.Reflection.Module`. dnlib has a dedicated method for this but AsmResolver only has `ModuleDefinition.FromModuleBaseAddress` without a clear explanation on how to get that base address.

## Proposal
The way dnlib seems to get the module base address is [by calling `Marshal.GetHINSTANCE`](https://github.com/0xd4d/dnlib/blob/master/src/DotNet/ModuleDefMD.cs#L228). I propose AsmResolver adds a `ModuleDefinition.FromModule` method that takes a `System.Reflection.Module` and automatically does this.

## Alternatives
- Add some xmldoc that clarifies where the module base address comes from.

**Comment by Washi1337** [comment]
Side note:

>Add some xmldoc that clarifies where the module base address comes from.

The [documentation](https://asmresolver.readthedocs.io/en/latest/peimage/basics.html#opening-a-pe-image) already states this, though perhaps it can be added to the xmldoc as well.
