### ISSUE TITLE
CilInstruction Next and Previous

### ISSUE THREAD

**Issue by dashne** [Washi1337/AsmResolver#24]
hi there, is there anyway to get CilInstruction.Next or CilInstruction.Previous?

**Comment by Washi1337** [comment]
I presume you are referring to the Instruction.Next and Instruction.Previous from Cecil. This can only be done by obtaining the index of the instruction, and adding to or subtracting one from it.

That being said, the `CilInstructionCollection` does have dedicated methods for finding the index of an instruction quite efficiently (O(log n)) if the offsets have been calculated.

For example:
```csharp
var instructions = methodBody.Instructions
...
int index = instructions.GetIndexByOffset(someInstruction);
var next = instructions[index + 1];
var previous = instructions[index - 1];
```

**Comment by dashne** [comment]
Thank you, I got it.
