### ISSUE TITLE
AsmResolver fails to resolve the correct overloaded method (Visual Basic).

### ISSUE THREAD

**Issue by N78750469** [Washi1337/AsmResolver#241]
## Describe the bug
AsmResolver resolves the wrong overloaded method, this is reproducible using vb .net because IsHideBySig isn't usually set.

## To Reproduce
Create a library, and a class with overloaded methods 

```
Public Class Class1

    Public Shared Sub Test(Arg As String)
        Console.WriteLine(Arg)
    End Sub
    Public Shared Sub Test(Arg As String, Arg2 As String)
        Console.WriteLine(Arg)
    End Sub
End Class
```

Import the library and call Test(Arg As String, Arg2 As String)

```
Imports ClassLibraryA

Module Program
    Sub Main(args As String())
        Console.WriteLine("Hello World!")
        Class1.Test("test", "test")
    End Sub
End Module

```

then resolve the call to Test

```
static MethodDefinition? ReproduceIssue(string path)
{
    var module = ModuleDefinition.FromFile(path);
    var secondCall = module.ManagedEntrypointMethod.CilMethodBody.Instructions.Where((x) => x.OpCode == CilOpCodes.Call).LastOrDefault();

    var calledMethod = secondCall.Operand as IMethodDefOrRef;
    return calledMethod.Resolve();
}
```
## Current behavior

```
{System.Void ClassLibraryA.Class1::Test(System.String)}
```

## Expected behavior
```
{System.Void ClassLibraryA.Class1::Test(System.String, System.String)}
```

## Platform
 - AsmResolver Version: 4.7.1

**Additional context**
According to Microsoft docs, even when it is valid to set IsHideBySig true the Visual basic version won't follow the same behavior as C#.

[# MethodBase.IsHideBySig Property - Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.methodbase.ishidebysig?view=net-6.0#:~:text=In%20the%20Visual%20Basic%20version%20of%20the%20code%20example,%20the%20IsHideBySig%20property%20returns%20false%20for%20the%20member%20in%20the%20derived%20class.%20In%20the%20C#%20version%20of%20the%20code%20sample,%20the%20property%20returns%20true%20for%20the%20member%20in%20the%20derived%20class.)

**Comment by Washi1337** [comment]
Good catch. Seems like I misinterpreted the semantics of the HideBySig flag.
