### ISSUE TITLE
VariableDefinition

### ISSUE THREAD

**Issue by dashne** [Washi1337/AsmResolver#26]
why there is no VariableDefinition like ParameterDefinition,MethodDefinition,..?

**Comment by Washi1337** [comment]
The main reasons are the following:

1. `ParameterDefinition`, `MethodDefinition` and the like are definitions found in the metadata tables, and they follow the names as described in the [ECMA-335](https://www.ecma-international.org/publications/standards/Ecma-335.htm) specification. Local variables are not stored in the metadata tables, but are rather stored as blob signatures. For this reason, it follows the same naming convention as other blob signatures (`VariableSignature`).
2. AsmResolver does not have PDB symbol read support. Therefore, AsmResolver would never be able to assign names to variables.

**Comment by dashne** [comment]
Is there any plan for adding  **PDB symbol read support** to AsmResolver ?

**Comment by Washi1337** [comment]
Not in AsmResolver 3 at least. It is on the todo list for 4, but does not have a high priority right now.
