### ISSUE TITLE
Load and Write, the file size of PresentationFramework.dll shrinks greatly

### ISSUE THREAD

**Issue by yangzhongke** [Washi1337/AsmResolver#267]
PresentationFramework.dll is a foundation library of WPF(.NET Core 6). The following code loads and write the file to a new file.

```
using AsmResolver.DotNet;

var sourceModule = ModuleDefinition.FromFile(@"E:\temp\PresentationFramework.dll");
sourceModule.Write(@"E:\temp\PresentationFramework.New.dll");
```

The file size of PresentationFramework.dll is 15.9MB, but, the file size of PresentationFramework.New.dll is 5.8MB only. It looks like that the file was corrupted, what happened?
![image](https://user-images.githubusercontent.com/13821363/158190148-983d081e-9a09-41b4-84ac-3dd8dd1e52d4.png)

I went through all the issues, but didn't find any answer.
Thanks.

**Comment by Washi1337** [comment]
This is expected, because .NET binaries that are part of the foundation are often AOT compiled using technologies such as NGEN, CrossGen or ReadyToRun. These types of binaries store both the managed code as well as the native code equivalent that was generated using a pre-JIT build step. In your case, it is a ReadyToRun binary.

Currently, AsmResolver does _not_ support these types of binaries out of the box, see some of the replies in #246 for some additional details. AsmResolver strips away the native part upon building the binary. This does not mean however that the binary gets corrupted in the process of building, As highlighted in the comments of that discussion, the managed code _should_ be kept intact. If, however, you see some structural differences within the managed part, then this can indeed be classified as a bug. Can you verify that this is the case?

**Comment by yangzhongke** [comment]
Thanks for your reply.
Dnlib provides a NativeWrite method to cope this issue, hope AsmResolver can provide it too.
I really appreciate your help.

**Comment by Washi1337** [comment]
Keep in mind that while dnlib provides a native writer, this is not always an optimal solution, depending on your usecase. 

As far as I know, the native writer of dnlib preserves as much of the PE as possible, adds additional sections to the executable if necessary, and never removes anything from the original binary. This means that upon writing the ReadyToRun module, the native code remains fully unchanged. This is problematic, as it still assumes the original structure even if you make structural changes to the associated managed code (both metadata and CIL). This means you would be effectively rendering the ReadyToRun structure inconsistent with the new structure. Keeping this around in the new binary therefore has little to no value, other than to inflate the binary size.

**Comment by yangzhongke** [comment]
Thanks for you kindly helping. I'm building a .NET trimming application [https://github.com/yangzhongke/Zack.DotNetTrimmer](https://github.com/yangzhongke/Zack.DotNetTrimmer). I have finished the removal of unused assebmlies, and I'm working on the removal of unused types from the used assebmlies. As what you mentioned, it's impossible to trim the assemblies which contains more than IL, so I should skip those assemblies. Right?
Thanks for you help again.

**Comment by yangzhongke** [comment]
I have tested it, what you said is corrent.
```csharp
using (ModuleDefMD mod = ModuleDefMD.Load(@"e:/temp/PresentationFramework.dll"))
{
    ClearModule(mod);
    mod.NativeWrite(@"e:/temp/PresentationFramework.new.dll");
}

void ClearModule(ModuleDefMD mod)
{
    foreach(var method in mod.Types.SelectMany(t=>t.Methods).Where(m=>m.Body!=null))
    {
        method.Body.ExceptionHandlers.Clear();
        method.Body.Instructions.Clear();
        method.Body.Variables.Clear();
        method.Body.Instructions.Add(new Instruction(OpCodes.Nop) { Offset = 0 });
        method.Body.Instructions.Add(new Instruction(OpCodes.Ldnull) { Offset = 1 });
        method.Body.Instructions.Add(new Instruction(OpCodes.Throw) { Offset = 2 });
    }
}
```
![a](https://user-images.githubusercontent.com/13821363/158507610-f49f989c-d7d3-4289-a298-4f65450117e3.png)

**Comment by Washi1337** [comment]
> As what you mentioned, it's impossible to trim the assemblies which contains more than IL, so I should skip those assemblies.

If you mean assemblies that follow the ReadyToRun / NGEN / CrossGen format, then yes it is currently not easy to edit (or trim) the existing native code using just AsmResolver. But as said before, stripping away the native code from these types of binaries does not necessarily render the application completely useless, as RTR binaries contain both the native code as well as the equivalent CIL code. Whether it is therefore good to skip the assembly is therefore up for debate, but it is definitely the safe option.

Side note: If you do decide on processing these files, you will probably need to clear the `ILLibrary` flag before saving the module. This ensures that the runtime does not attempt to load the binary as an image with a native RTR header (see https://github.com/dotnet/runtime/blob/main/src/coreclr/utilcode/pedecoder.cpp#L1076)

```csharp
var module = ModuleDefiniition.FromFile("input.dll");
// ...
module.Attributes &= ~DotNetDirectoryFlags.ILLibrary;
module.Write("output.dll");
```

**Comment by yangzhongke** [comment]
Thanks for your reply. You're so helpful.
