### ISSUE TITLE
ReferenceImporter::ImportTypeSignature is not recursive

### ISSUE THREAD

**Issue by SamboyCoding** [Washi1337/AsmResolver#268]
## Describe the bug
Disclaimer - I'm not sure if this is a bug or intended behavior, but it would be nice if it could be changed.

Given, for example, a `GenericInstanceTypeSignature`, importing this into a module using `module.Assembly.GetImporter().ImportTypeSignature` does not import at least the base type, and possibly not the generic parameters, of the signature, resulting in, for example, the following output:

```
Construction of the PE image failed with one or more errors. (Member System.Collections.Generic.KeyValuePair`2 was not imported into the module.)
```

## To Reproduce
Create a `GenericInstanceTypeSignature` of `KeyValuePair<string, string>`, something like so

```cs
//corlibModule is the manifest ModuleDefinition of a .net framework mscorlib assembly.
var kvpType = corlibModule.TopLevelTypes.First(t => t.FullName == "System.Collections.Generic.KeyValuePair`2");
var stringType = corlibModule.TopLevelTypes.First(t => t.FullName == "System.String");
var git = new GenericInstanceTypeSignature(kvpType, false);
git.TypeArguments.Add(stringType.ToTypeSignature());
git.TypeArguments.Add(stringType.ToTypeSignature());
```

Next, import this into another module using ImportTypeSignature, and use the resulting type signature in, for example, a parameter for a method. Then attempt to save the generated assembly.

## Expected behavior
No errors are thrown - all required types are imported into the destination module, and the module is written successfully.

## Screenshots
N/A

## Platform
 - OS: Windows 11
 - AsmResolver Version: 4.9.0

**Additional context**
The same "issue" occurs with Mono.Cecil, except that also doesn't import generic argument types either. Not sure if AsmResolver is importing the argument types or not, but the error I get only mentions the base type - KeyValuePair, in this case.

**Comment by SamboyCoding** [comment]
Whoops, I just realised GetImporter() is my own extension function, but all it does is define and cache a ReferenceImporter for the first module in an assembly.

**Comment by Washi1337** [comment]
Seems I cannot reproduce this issue. The following code works fine on my end. Are you sure you are adding the right type to the right module?

```csharp
var module = ModuleDefinition.FromFile(typeof(Program).Assembly.Location);
var corlibModule = module.MetadataResolver.AssemblyResolver.Resolve(KnownCorLibs.SystemPrivateCoreLib_v6_0_0_0).ManifestModule;

var kvpType = corlibModule.TopLevelTypes.First(t => t.FullName == "System.Collections.Generic.KeyValuePair`2");
var stringType = corlibModule.TopLevelTypes.First(t => t.FullName == "System.String");
var git = kvpType.MakeGenericInstanceType(
    stringType.ToTypeSignature(),
    stringType.ToTypeSignature());

var importer = new ReferenceImporter(module);
var method = new MethodDefinition(
    "Foo",
    MethodAttributes.Static,
    MethodSignature.CreateStatic(
        module.CorLibTypeFactory.Void,
        importer.ImportTypeSignature(git)));

module.GetOrCreateModuleType().Methods.Add(method);
module.Write("/tmp/output.dll");
````

**Comment by Washi1337** [comment]
I am still seeing the same (working) results on my end. Below creates the following method:

```csharp
System.Void Foo(System.Collections.Generic.List`1<System.Collections.Generic.KeyValuePair`2<System.IO.Stream, System.IO.Stream>>)
```
I have tried this with both a .NET 6.0 assembly (System.Private.CoreLib 6.0.0.0), as well as a .NET Framework 4.7.2. binary (mscorlib 4.0.0.0), and in both situations no import errors occur.

```csharp
var module = ModuleDefinition.FromFile(typeof(Program).Assembly.Location);
var corlibModule = module.MetadataResolver.AssemblyResolver.Resolve(KnownCorLibs.SystemPrivateCoreLib_v6_0_0_0).ManifestModule!;

var listType = corlibModule.TopLevelTypes.First(t => t.FullName == "System.Collections.Generic.List`1");
var kvpType = corlibModule.TopLevelTypes.First(t => t.FullName == "System.Collections.Generic.KeyValuePair`2");
var streamType = corlibModule.TopLevelTypes.First(t => t.FullName == "System.IO.Stream");
var git = listType.MakeGenericInstanceType(
    kvpType.MakeGenericInstanceType(
        streamType.ToTypeSignature(),
        streamType.ToTypeSignature()
    )
);

var importer = new ReferenceImporter(module);
var method = new MethodDefinition(
    "Foo",
    MethodAttributes.Static,
    MethodSignature.CreateStatic(
        module.CorLibTypeFactory.Void,
        importer.ImportTypeSignature(git)));

module.GetOrCreateModuleType().Methods.Add(method);
module.Write("/tmp/output.dll");
```

**Comment by SamboyCoding** [comment]
One specific case I've got is the field `System.Xml.Linq.XHashtable`1<System.WeakReference> System.Xml.Linq.XNamespace::namespaces` (which is in System.Xml.Linq.dll), where System.WeakReference is not being imported from mscorlib, as you can see below: 

![image](https://user-images.githubusercontent.com/7011721/158659860-acbae741-a8eb-4feb-94c9-e58add4c4a9c.png)

The field is being defined like so 
![image](https://user-images.githubusercontent.com/7011721/158659922-7f923db1-49ea-48b8-a8c9-3306510332e9.png)

**Comment by SamboyCoding** [comment]
Could the issue possibly be due to the difference between calling MakeGenericInstanceType and manually constructing a GenericInstanceTypeSignature?

**Comment by SamboyCoding** [comment]
Yeah, that's all correct. I'll debug the problem in more detail now and see if I can't work out what's going on

**Comment by SamboyCoding** [comment]
Aha, I've found the issue. ReferenceImporter ImportTypeSignature checks if type.Module == this.TargetModule, and if so, returns the type immediately. Which, in this case, returns true, because the top-level type, XHashtable, is defined in this module, but the generic type argument, WeakReference, is not, so it needs to be imported anyway.

**Comment by SamboyCoding** [comment]
XHashtable is declared in the same type as the field in question

**Comment by SamboyCoding** [comment]
Yes I can confirm 274 fixes this issue - I no longer have to import the components of a generic instance type prior to constructing it.
