### ISSUE TITLE
[Question]: Why are interfaces used for private fields?

### ISSUE THREAD

**Issue by ds5678** [Washi1337/AsmResolver#271]
I noticed that some places in the code use an interface as the field type for private fields. One example location is here:

https://github.com/Washi1337/AsmResolver/blob/7cb4ae9b547a9a638c21107118239249de6ae5bf/src/AsmResolver.DotNet/DefaultMetadataResolver.cs#L14

As I understand things, interface calls are even less performant than virtual calls, so in this example, using a `Dictionary` or `ConcurrentDictionary` would improve performance. Making changes like this across the whole project could be a significant difference.

Is this something that you're open to?

**Comment by Washi1337** [comment]
Short answer: Yes I would be open to changes like these.

Longer answer: A lot of these are leftovers of encapsulations that eventually got demoted back to fields, or are simply the result of a lack of programming knowledge on where to use interfaces and where not to use them. AsmResolver is a project running for a while already, and as it grows, I have learned along the way as well. Some of these redundant abstractions are already removed and concretized into their specific implementations. But as you can see not all of them yet.

**Comment by ds5678** [comment]
I'll see what I can find and make a PR.

I'm not judging you. I just want this to be the best it can be.

**Comment by Washi1337** [comment]
Don't worry, I didn't get the impression you were. I am simply giving you the answer to your post title ;)
