### ISSUE TITLE
Method Overrides

### ISSUE THREAD

**Issue by dashne** [Washi1337/AsmResolver#29]
Hi there, I have two questions,:
1. if I have a MethodDefinition that has overrides, how to get overrides from method definition?
2. how to check if a method return type has FieldMarshal?, this might be strange , but I saw some codes from Mono Cecil the checking FieldMarshal availability with methodReturnType!.
sample Code would be very helpful.

Thanks

**Comment by Washi1337** [comment]
Hi,

1. In the .NET file format there is no special record for overriding a method (there is only one for explicit interface implementations). AsmResolver 3 therefore also hasn't any built-in feature for it. You'd have to search derived classes yourself, and find methods that match the signature of your virtual/abstract method. For member comparisons you can use the `SignatureComparer` class.

2. As per ECMA-335, FieldMarshal can only be added to a HasFieldMarshal member, which is either a field or a parameter definition. Therefore to assign custom attributes or field marshalling rules for return method values, the compiler adds an auxiliary parameter definition with sequence = 0, and assigns the data to this parameter.

```csharp
var returnParameter = methodDef.Parameters.FirstOrDefault(p => p.Sequence == 0);
if (returnParameter != null)
{
   var fieldMarshal = returnParameter.FieldMarshal;
}
```

Hope it helps!

**Comment by dashne** [comment]
Thank you,please could you provide a sample code for reply  no. 1?

**Comment by Washi1337** [comment]
Something in the lines of the following could work:

```csharp
private static IEnumerable<MethodDefinition> FindOverrides(ModuleDefinition targetModule,
    MethodDefinition abstractMethod)
{
    var eligibleTypes = targetModule
        .GetAllTypes()
        .Where(t => IsDerivedFrom(t, abstractMethod.DeclaringType));

    var comparer = new SignatureComparer();
    var overrides = new List<MethodDefinition>();
    foreach (var type in eligibleTypes)
    {
        var overrideMethod = type.Methods.FirstOrDefault(m =>
            m.Name == abstractMethod.Name && m.IsVirtual && comparer.Equals(m.Signature, abstractMethod.Signature));
        if (overrideMethod != null)
            overrides.Add(overrideMethod);

    }

    return overrides;
}

private static bool IsDerivedFrom(TypeDefinition type, ITypeDefOrRef baseType)
{
    while (type != null)
    {
        if (type.IsTypeOf(baseType.Namespace, baseType.Name))
            return true;
        type = type.BaseType?.Resolve() as TypeDefinition;
    }

    return false;
}
```

**Comment by dashne** [comment]
Thank you so much, its really helping me a lot.
But I faced another issue when I reviewed PropertyDefinition and it is not referencing Interface IMemberDefinition,is'nt it suppose to reference IMemberDefinition too? if not, can I add it my self and recompile it,does it make any problem?

**Comment by Washi1337** [comment]
Feel free to add an implementation for it ;)

**Comment by Washi1337** [comment]
Closed for inactivity.
