### ISSUE TITLE
ReferenceImporter ImportField(FieldInfo)  produces invalid MemberReferene

### ISSUE THREAD

**Issue by JPaja** [Washi1337/AsmResolver#307]
## Describe the bug
Member references generated using importer.ImportField(fieldInfo); are not resolvable.

Resolver fails when trying to compare field signature attributes
where imported field signature attributes are StdCall | FastCall | Field | HasThis
but original only have Field flag.

## To Reproduce
```csharp
using System.Linq;
using Xunit;

namespace AsmResolver.DotNet.Tests;

public class BadFieldImporterTests
{
    public FieldDefinition Field;

    [Fact]
    public void BadImportTest()
    {
        var module = ModuleDefinition.FromFile(typeof(BadFieldImporterTests).Assembly.Location);
        var field = module.GetAllTypes()
            .SingleOrDefault(t => t.Name == nameof(BadFieldImporterTests))!
            .Fields
            .SingleOrDefault(f=>f.Name == nameof(Field));

        var fieldInfo = typeof(BadFieldImporterTests).GetField(nameof(Field));
        
        var importer = new ReferenceImporter(module);
        var imported = importer.ImportField(fieldInfo!);
        var resolved = imported.Resolve();

        Assert.NotNull(resolved);
        Assert.Equal(field, resolved);
    }
}

```

## Platform
 - OS: Windows 10
 - AsmResolver Version: 4.10 / development branch

**Additional context**
Reflection also fails to handle resolving these imported member references

**Comment by Washi1337** [comment]
This seems to be a leftover after deprecating field signature factory methods (see #254).
