### ISSUE TITLE
Assembly EntryPoint

### ISSUE THREAD

**Issue by dashne** [Washi1337/AsmResolver#31]
how to get Method `EntryPoint ` from `MethodDefinition` ?

**Comment by Washi1337** [comment]
Not sure what you're referring to here. Can you please elaborate?

**Comment by dashne** [comment]
Sorry,My Question was : how to get Assembly `EntryPoint `from `MethodDefinition `?, like Mono cecil `Assembly.EntryPoint`.
I have another question: is there any way to get `ParameterDefinition `or even parameter Name from
`ParameterSignature`, because `CilInstruction `Operand is Only gives `ParameterSignature`

**Comment by Washi1337** [comment]
MetadataImage has a ManagedEntrypoint property.

The only way to get the actual name of the parameter is to first obtain its index using MethodSignature.Parameters.IndexOf, and then use this index to get the right parameter definition from MethodDefinition.Parameters
