### ISSUE TITLE
Windows Assembly Runtime

### ISSUE THREAD

**Issue by dashne** [Washi1337/AsmResolver#32]
how to find out if an `AssemblyReference `is Windows Runtime Assembly?

**Comment by Washi1337** [comment]
There is no direct property for it (yet). You can resolve the assembly reference to a definition, and then compare the `VersionString`  property in the underlying metadata header. For WinMD assemblies, it should contain start with the string `WindowsRuntime`, followed by the version number.

Source: [adapter.cpp from dotnet/runtime](https://github.com/dotnet/runtime/blob/master/src/coreclr/src/md/winmd/adapter.cpp#L86)

**Comment by Washi1337** [comment]
Actually, it can be done without resolving the assembly. It is encoded in the assembly attributes with a that AsmResolver 3 does not define yet.

```csharp
bool isWindowsRuntime = (assembly.Attributes & 0x0E00) == 0x200;
```

Note that v4 does indeed define these constants.

Source: https://github.com/dotnet/runtime/blob/master/src/coreclr/src/inc/corhdr.h#L767
