### ISSUE TITLE
Assembly file type

### ISSUE THREAD

**Issue by dashne** [Washi1337/AsmResolver#34]
How to find out where an assembly is Windows (exe), Console(exe), or Library (.dll)?

**Comment by Washi1337** [comment]
Hi,

The file header of an assembly contains the Characteristics property. For libraries, the `Dll` bit is set.

Additionally, the optional header of an assembly contains the SubSystem property. This can tell you whether the executable file's subsystem is Console or Windows.

**Comment by dashne** [comment]
Thank you,another question: how to find if an assembly compiled as `Any Cpu` Architecture?

**Comment by Washi1337** [comment]
AnyCPU binaries have the `Bit32Required` field set to zero in the NET directory's `Flags` property, as well as the `Magic` in the optional header set to `Pe32`.

**Comment by Washi1337** [comment]
Closed for inactivity.
