### ISSUE TITLE
Unhandled Exception: System.DivideByZeroException

### ISSUE THREAD

**Issue by ttodua** [Washi1337/AsmResolver#340]
### AsmResolver Version

4.11.2

### Operating System

Windows

### Describe the Bug

```
Unhandled Exception: System.DivideByZeroException: Attempted to divide by zero.
   at AsmResolver.DotNet.Builder.ManagedPEImageBuilder..ctor() 
``` 

### How To Reproduce

it's complex and comes from some other apps, at this moment I am unable to write down reproduce steps. Just I need any possible thought/hint from you, what/how that exception could be happening

### Expected Behavior

n/a

### Actual Behavior

n/a

### Additional Context

thanks in advance.

**Comment by Washi1337** [comment]
This is going to be very hard to say without any hint of a sample binary, sample code or at least a full stack trace. Your partial stack trace indicates one of `ManagedPEImageBuilder`'s constructors is throwing it, but as far as I see it don't do any divisions directly happening in the code for that, so I am as much at a loss at you at the moment :)

**Comment by ttodua** [comment]
do you have discord or any private channel, where i can send full details for reproduce?

**Comment by Washi1337** [comment]
There is an official Discord, see https://github.com/Washi1337/AsmResolver/discussions/291. 

If you need to send samples that you do not wish to share publicly, you can send them to the mail address that you can find on my GitHub profile.

**Comment by ttodua** [comment]
thanks!

**Comment by Washi1337** [comment]
The instructions for both samples you gave me over mail indicate that this is not an issue of AsmResolver but an issue of the third party program (JitDumper) that uses it.

As far as I understand, JitDumper places hooks within the JIT compiler to get access to various internal CLR structures. If done incorrectly, this can screw up a lot of things and cause many spurious exceptions to be thrown. A quick look with WinDBG confirms this; the error indeed seems to come from within the JIT compilation itself, and not from within AsmResolver's code. I can therefore quite confidently say this is not a bug within AsmResolver, but an unintentional artifact that is introduced by JitDumper.

I do not maintain JitDumper and don't know many of its internals. As such, this is out of my control nor something I can fix by updating AsmResolver. You will have to contact the maintainer of JitDumper and see if he can investigate more.

**Comment by ttodua** [comment]
I'll pass your comment to whoever concerns.
thank you for the attentive support!
