### ISSUE TITLE
Rebuilding an AssemblyDefinition results in CorLib reference being null 

### ISSUE THREAD

**Issue by 766F6964** [Washi1337/AsmResolver#39]
**System:**
System: Tested on Arch Linux x64
Kernel: 5.5.8-arch1-1
DotNet Version: 3.1.102
AsmResolver Branch: v4

**Summary:**
When creating a new _AssemblyDefinition_ and rebuilding it in memory, the reading process of the _AssemblyDefinition_ fails, because the _corLib_ parameter in the _CreateAssemblyResolver_ method in the _ModuleDefinition_ class is null. 

**Steps to reproduce:**
1. Create a new AssemblyDefinition from scratch:
```csharp
var assembly = new AssemblyDefinition("Test", new Version(1, 0, 0, 0));
var module = new ModuleDefinition("TestModule");
assembly.Modules.Add(module);
```
2. Rebuild the _AssemblyDefinition_:
```csharp
public AssemblyDefinition Rebuild(AssemblyDefinition assemblyDefinition)
{
    using var stream = new MemoryStream();
    assemblyDefinition.ManifestModule.Write(stream);
    return AssemblyDefinition.FromReader(new ByteArrayReader(stream.ToArray()));
}
```
3. Observe AsmResolver crash when reading the rebuilt _AssemblyDefinition_ from the stream.

**Possible cause:**
Somehow, it seems that _AssemblyReferences_ are not processed/loaded correctly when reading an _AssemblyDefinition_. (See: FindMostRecentCorLib() in SerializedModuleDefinition.cs)

**Comment by Washi1337** [comment]
Should be fixed now.
