### ISSUE TITLE
Generic [Try]LookupMember<T> overloads

### ISSUE THREAD

**Issue by Washi1337** [Washi1337/AsmResolver#392]
### Problem Description

Currently, `ModuleDefinition.LookupMember` is a very generic function that returns a `IMetadataMember` when the call is successful. If the type of the member is already known (e.g., because the provided metadata token has a known table index), this often requires extra type-casts or type-checks at the call-site. This can make code less readable / concise:

```csharp
var type = (TypeDefinition) module.LookupMember(token);
```

```csharp
if (module.TryLookupMember(token, out var member) && member is TypeDefinition type) 
{
   /* ... Use `type`  ...*
}
```

### Proposal

Add generic overloads `LookupMember<T>(MetadataToken)` and `TryLookupMember<T>(MetadataToken, out T)`, that also try to cast the resolved member to the specified type parameter, such that the type inference of the C# compiler can take over, replacing the explicit or safe type-casts:

```csharp
var type = module.LookupMember<TypeDefinition>(token);
```

```csharp
if (module.TryLookupMember(token, out TypeDefinition type)) 
{
   /* ... Use `type`  ...*
}
```

### Alternatives

C# Pattern matching is pretty decent nowadays and could be combined with the original versions of `LookupMember`, but this still is not as concise as it could be.

### Additional Context

This is extra nice if it is used in a chain of calls, avoiding many parentheses. For example:

```csharp
var cctor = ((TypeDefinition) module.LookupMember(token))
    .Methods.First(m => m.IsConstructor && m.IsStatic);
```

versus: 

```csharp
var cctor = module.LookupMember<TypeDefinition>(token)
    .Methods.First(m => m.IsConstructor && m.IsStatic);
```

**Comment by sunnamed434** [comment]
Oh, yeah, I do like it
