### ISSUE TITLE
How to get RVA of added section

### ISSUE THREAD

**Issue by caizhe666** [Washi1337/AsmResolver#409]
### Description

I added a section with some content to a `PEFile` and I have to get the RVA of the section in order to set new `AddressOfEntryPoint`, but I found that both `AddedContent.Rva` and `AddedSection.Rva` are always 0x1000

Here is my code:
```
var AddedContent = /* Some content */
var AddedSection = new PESection(".hack", SectionFlags.ContentCode | SectionFlags.MemoryRead | SectionFlags.MemoryExecute);
AddedSection.Contents = AddedContent;

OriginalFile.Sections.Add(AddedSection);
OriginalFile.OptionalHeader.AddressOfEntryPoint = AddedContent.Rva + CodeEntryPointOffset;
// OriginalFile.OptionalHeader.AddressOfEntryPoint = AddedSection.Rva + CodeEntryPointOffset;
// Both always 0x1000

OriginalFile.Write(@".\Modified.exe");
```

![image](https://user-images.githubusercontent.com/47047883/215997057-fce6e336-cc47-4f09-b303-08c3e432a267.png)

**Comment by Washi1337** [comment]
For performance reasons, AsmResolver does not calculate offsets and sizes unless you tell it to. Thus, make sure that you align all sections accordingly before you retrieve their new RVAs. This can be done either by calling `OriginalFile.UpdateHeaders()` or `OriginalFile.AlignSections()`. Both of them calculate offsets, and have slightly different meanings. You can refer to the the xmldocs attached to these methods to figure out these differences.
