### ISSUE TITLE
Add member cloning functionality?

### ISSUE THREAD

**Issue by 766F6964** [Washi1337/AsmResolver#42]
One feature that AsmResolver is still missing, but could be really useful is a member cloner.
Let me demonstrate a scenario where a member cloner would be very beneficial:

Suppose you develop an application that processes/analyzes assemblies, such as a deobfuscator.
You'd like to write unit tests for this application, but you notice there could be a lot (maybe hundreds) of very specific cases that you should cover.
In other words, you need to generate hundreds of very specific dummy assemblies to test against.
Currently, you only have two ways of achieving this:

**Option 1:**
To craft these tests you build a new assembly from scratch in every test case.
You create new TypeDefinitions, MethodDefinitions, FieldDefinitions with the properties you want to test against, and add them to your assembly.
While this approach allows you to generate isolated test assemblies for the specific cases you'd like to cover, it also comes with some downsides:
Test cases become really long and unreadable, and also you (most likely) will end up with a lot of duplicate code across your test cases.

**Option 2:**
You add 100 new projects to your project solution to account for your 100 test scenarios. While this still ensures isolation between tests, it is just as bad as the first option.
You not only have to compile 100's of different projects, which takes a long time, but again, you generate a lot of duplicate code.

So, instead I propose a different approach, that ensures concise, easily readable test cases, while still ensuring isolation and decent compile times: Dynamically generating test assemblies with a member cloner.

You'd have only one additional project in your solution which contains all the scenarios you'd like to test as classes.
In the tests, you'd generate an empty dummy assembly, and use a member cloner to clone the test classes from the test project and add them to your generated assembly.
This would keep the tests concise, readable and still ensures isolation.
The creation of a specific assembly in a unit test could then look like this:

```csharp
var tempAssembly = new TempAssemblyBuilder(templateAssembly)
.IncludeType(nameof(Class1))
.ExcludeMethod(nameof(Class1.Method1))
.IncludeType(nameof(Class2))
.Build()
```

**Comment by Washi1337** [comment]
This has been implemented and merged with the v4 branch :)
