### ISSUE TITLE
CilInstruction.Offset is always 0

### ISSUE THREAD

**Issue by AnErrupTion** [Washi1337/AsmResolver#426]
### AsmResolver Version

5.2.0

### .NET Version

.NET 7.0

### Operating System

Linux

### Describe the Bug

When adding instructions to a method then printing the offset of all of them, they are all equal to 0. This doesn't actually affect code generation, since the code generates correctly, but it's just the Offset field that is always equal to 0.

### How To Reproduce

Here is sample code that triggers the bug:

```cs
using AsmResolver.DotNet;
using AsmResolver.DotNet.Signatures;
using AsmResolver.PE.DotNet.Cil;
using AsmResolver.PE.DotNet.Metadata.Tables.Rows;

var module = new ModuleDefinition("module");
var method = new MethodDefinition("test", MethodAttributes.Static, MethodSignature.CreateStatic(module.CorLibTypeFactory.Void));

method.CilMethodBody = new(method);
method.CilMethodBody.Instructions.Add(CilOpCodes.Ldc_I4_2);
method.CilMethodBody.Instructions.Add(CilOpCodes.Stloc_0);
method.CilMethodBody.Instructions.Add(CilOpCodes.Ret);

foreach (var instruction in method.CilMethodBody.Instructions)
{
    Console.WriteLine(instruction.ToString());
}
```

### Expected Behavior

It should print something like:

```
0
4
8
```

### Actual Behavior

The sample code prints:
```
0
0
0
```

**Comment by Washi1337** [comment]
For performance reasons, offsets are not automatically calculated. You can trigger offset calculation using `Instructions.CalculateOffsets()`.

See also: https://asmresolver.readthedocs.io/en/latest/dotnet/managed-method-bodies.html#finding-instructions-by-offset

**Comment by AnErrupTion** [comment]
> For performance reasons, offsets are not automatically calculated. You can trigger offset calculation using `Instructions.CalculateOffsets()`.
> 
> See also: https://asmresolver.readthedocs.io/en/latest/dotnet/managed-method-bodies.html#finding-instructions-by-offset

Why not calculate them each time an instruction is added to the list? Does this still cause performance issues?

**Comment by Washi1337** [comment]
> Why not calculate them each time an instruction is added to the list? Does this still cause performance issues?

@AnErrupTion Yes. Calculating the offset of a new instruction at the end of the list may be relatively easy (i.e., just get the last instruction's offset + size), but anything more substantial (e.g., inserting in the middle or removing an instruction) will require an O(n) operation to refresh all offsets. Given that typically offsets aren't really that important in CIL anyways, this design choice was made.

**Comment by AnErrupTion** [comment]
> > Why not calculate them each time an instruction is added to the list? Does this still cause performance issues?
> 
> @AnErrupTion Yes. Calculating the offset of a new instruction at the end of the list may be relatively easy (i.e., just get the last instruction's offset + size), but anything more substantial (e.g., inserting in the middle or removing an instruction) will require an O(n) operation to refresh all offsets. Given that typically offsets aren't really that important in CIL anyways, this design choice was made.

That makes sense :p
