### ISSUE TITLE
TypeMemoryLayout + GenericInst struct = Infinity Loop

### ISSUE THREAD

**Issue by BadRyuner** [Washi1337/AsmResolver#447]
### AsmResolver Version

5.3.0

### .NET Version

6.0

### Operating System

Windows

### Describe the Bug

When you create TypeMemoryLayout for GenericInstanceTypeSignature ValueType, you get an infinite loop . Since the CPU load at this time is 100% (for one core), I think that the creation of TypeMemoryLayout goes into an infinite loop.

### How To Reproduce

```csharp
GenericInstanceTypeSignature gist = ...; // In my case: List<!0>.Enumerator
var size = gist.GetImpliedMemoryLayout(false).Size; // infinity loop
```
Also if you change the parameters and pass List<int>.Enumerator, it will also die.

### Expected Behavior

Get the size of the entire GenericTypeInstance.

### Actual Behavior

Infinite Loop.

**Comment by BadRyuner** [comment]
It doesn't loop anymore.

**Comment by Washi1337** [comment]
Perfect, it will be part of 5.4.0 then :+1:
