### ISSUE TITLE
Suppress BadImageFormatException

### ISSUE THREAD

**Issue by sunnamed434** [Washi1337/AsmResolver#476]
### Problem Description

This is similar to dnlib, when `verify` is set to false it will not going to make some checks to prevent the `BadImageFormatException`, because some images for example Mono will be loaded typically but when using the custom HotReload via AsmResolver it could cause problems

[Examples from dnlib](https://github.com/search?q=repo%3A0xd4d%2Fdnlib%20%20BadImageFormatException&type=code)

### Proposal

Let's say when you're creating an instance of the PEImage via factory you can pass the `verify`

[Example](https://github.com/Washi1337/AsmResolver/blob/d954be07d8dabcbcd2e97e521342d9f6213dca2e/src/AsmResolver.PE.File/SerializedPEFile.cs#L35-L36)
```cs
public SerializedPEFile(in BinaryStreamReader reader, PEMappingMode mode, bool verify)

if (verify && signature != ValidPESignature)
throw new BadImageFormatException();
```

**Comment by Washi1337** [comment]
Coils you give a concrete (reproducible) example for which this is necessary? I do not quite see why we would want to open fully invalid binaries that wouldn't load anyways by the PE loader or CLR itself due to an invalid PE magic signature.

**Comment by Washi1337** [comment]
Closed for inactivity. Feel free to comment again if you have a concrete example for which this may be needed.

**Comment by sunnamed434** [comment]
For example, dnlib has this thing, you can ignore those errors, for example, I use AsmResolver for hotreload and I load a bunch of assemblies some of them protected via BitMono and they just won't load, what I need to do is perhaps use Lib.Harmony NuGet package, or another way to patch AsmResolver

**Comment by Washi1337** [comment]
I don't see how a hot-reload causes an invalid PE signature?

A PE does not run without a valid PE signature. At least within the context of the normal Windows PE loader or .NET runtime host. Mono also does not seem to accept any PE without the MZ or NT PE signature present (on linux).

Can you give me a concrete example that can also be tested or reproduced for which this is the case?  I am trying to figure out whether this is really worth the refactor.

**Comment by sunnamed434** [comment]
You got me wrong, I don't mean that hot-reload caused an invalid PE signature, it can be caused by BitMono for example, or another tool, but what if I just want to load a file by ignoring all of those things?
