### ISSUE TITLE
Enhancement: Add a Location property to Assembly- and/or ModuleDefintion

### ISSUE THREAD

**Issue by zsr2531** [Washi1337/AsmResolver#49]
**Summary:**
It would be useful to know the full path of an Assembly/Module Definition

**Suggested Syntax:**
```cs
AssemblyDefintion asm = ...
ModuleDefinition mod = ...

string asmPath = asm.Location;
string modPath = mod.Location;
```

**Requirements:**
- Add a Location property to Assembly/Module Definition

**Comment by Washi1337** [comment]
Modules are assigned a file path when loaded using `ModuleDefinition.FromFile`

```csharp
var module = ModuleDefinition.FromFile(@"C:\file.exe");
string path = module.FilePath; // returns @"C:\file.exe"
```

.NET assemblies might consist of multiple files, so the way I see it there's a couple of options:
- Add `FilePath` property to `AssemblyDefinition`, and let it return the file path of the manifest module
- Add `GetFilePaths()` method that obtains all file paths of all defined modules.
- Don't add a file path property or method at all to `AssemblyDefinition`.

**Comment by zsr2531** [comment]
Closing, was blind and didn't see the FilePath property at all.
