### ISSUE TITLE
Add shortcut to check if a method is a property getter or setter

### ISSUE THREAD

**Issue by 766F6964** [Washi1337/AsmResolver#54]
Given a _MethodDefinition_, we want to check if it is part of a property semantic, - meaning if the method is a getter or a setter of a _PropertyDefinition_.

Please add a `.IsGetMethod` and `.IsSetMethod` property to the _MethodDefinition_ class.

**Comment by Washi1337** [comment]
For consistency, this would also mean  `IsAddMethod`, `IsRemoveMethod` `IsFireMethod` would have to be added for event definitions.

Perhaps it is also an idea to include some kind of `ParentSemantics` property to `MethodDefinition` that also immediately obtains either the parent `PropertyDefinition` or `EventDefinition`. Thoughts? Maybe you have a better name for such a property?

**Comment by 766F6964** [comment]
`ParentSemantics` or `ParentMemberSemantics` is fine. 
And yeah, as you stated, the same should be added for EventDefinitions.

**Comment by Washi1337** [comment]
Added in 799d7997d6d0cfc832c1224621824837e12f9680

Changed `ParentSemantics` to just `Semantics`, returning the `MethodSemantics` object that is associated to the method. You can get the property or event using the `Association` property of this semantics object.
