### ISSUE TITLE
Not Work with Tinysharp

### ISSUE THREAD

**Issue by steve02081504** [Washi1337/AsmResolver#541]
### AsmResolver Version

5.5.1.0

### .NET Version

8.0.1

### Operating System

Windows

### Describe the Bug

An error exe is generated when reading and rewriting a program generated by Tinysharp.
Its not a big deal. So okay not to fix it if y want.

### How To Reproduce

```pwsh
~ >'"Hello 世界！👾"' | ps12exe
Compiled file written -> 1024 bytes
~ >./a.exe
Hello 世界！👾
~ >Get-ChildItem ~/workstation/pwshProjs/ps12exe/src/bin/AsmResolver | ForEach-Object { Add-Type -LiteralPath $_ }
~ >$file = [AsmResolver.PE.PEImage]::FromFile('.\a.exe')
~ >$Builder = New-Object AsmResolver.PE.DotNet.Builder.ManagedPEFileBuilder
~ >$file = $builder.CreateFile($file)
~ >$file.Write('.\a.exe')
~ >./a.exe
爮汥捯
䀀ȀЀ
~ >
```

### Expected Behavior

> Hello 世界！👾

### Actual Behavior

> 爮汥捯
> 䀀ȀЀ

### Additional Context

![图片](https://github.com/Washi1337/AsmResolver/assets/31927825/3a35d6d4-7403-4b91-848d-74bb939528e9)

**Comment by Washi1337** [comment]
This is by design. `ManagedPEFileBuilder` does a full reconstruction of the PE and does not necessarily preserve existing segments unless you explicitly tell it to do as such.

**Comment by steve02081504** [comment]
got it!
txh for explaning.
