### ISSUE TITLE
CI and Artifacts?

### ISSUE THREAD

**Issue by steve02081504** [Washi1337/AsmResolver#542]
### Description

Sometimes people want to download binaries built from the latest commit to experience the latest features.
But as of now I don't see any GitHub actions in the repo, we can only build the latest version by local compilation, and no auto test each commit.
Is there a reason for this? Or just didn't get around to setting it up?
I can submit a PR if you wish.

**Comment by Washi1337** [comment]
Commits are built, tested and uploaded via [AppVeyor](https://ci.appveyor.com/project/Washi1337/asmresolver/branch/development/artifacts).
