### ISSUE TITLE
GetLocalVariable() fails to process instructions with byte operands

### ISSUE THREAD

**Issue by 766F6964** [Washi1337/AsmResolver#55]
**System**:
System: Tested on Arch Linux x64
Kernel: 5.6.2-arch1-2
DotNet Version: 3.1.103
AsmResolver Branch: v4

**Summary:**
Instructions such as `Ldloc`, `Ldloc_S`, `Stloc` and `Stloc_S` are [processed incorrectly](https://github.com/Washi1337/AsmResolver/blob/v4/src/AsmResolver.DotNet/Code/Cil/CilInstructionExtensions.cs#L166-L170) when the instruction operand is of type _System.Byte_.
Casting the operand triggers an _InvalidCastException_:
```
System.InvalidCastException: Unable to cast object of type 'System.Byte' to type 'AsmResolver.DotNet.Code.Cil.CilLocalVariable'.
``` 
 The same problem probably also applies when the operand is of type `System.SByte`.

**Steps to reproduce:**
Call `GetLocalVariable` on an instruction with the following form:

![2020-04-09-171242_406x124_scrot](https://user-images.githubusercontent.com/34845270/78910520-61e72a00-7a85-11ea-9511-f9ff7e7180f4.png)

**Comment by Washi1337** [comment]
Good catch. Should be fixed now.
