### ISSUE TITLE
GetHashCode for FunctionPointerTypeSignature is not implemented

### ISSUE THREAD

**Issue by BadRyuner** [Washi1337/AsmResolver#551]
### AsmResolver Version

5.5.1

### .NET Version

Any

### Operating System

Windows

### Describe the Bug

Hashset is not friendly with FunctionPointerTypeSignature
[Target site](https://github.com/Washi1337/AsmResolver/blob/master/src/AsmResolver.DotNet/Signatures/SignatureComparer.TypeSignature.cs#L102)

### How To Reproduce

```csharp
var somemodule = new ModuleDefinition("heh");
var ty = somemodule.CorLibTypeFactory;
HashSet<TypeSignature> hashset = new HashSet<TypeSignature>(SignatureComparer.Default);
var somefnsig = new FunctionPointerTypeSignature(MethodSignature.CreateStatic(ty.Int64));
hashset.Add(somefnsig); // <--- System.NotSupportedException: "Specified method is not supported."
```

### Expected Behavior

Not to see NotSupportedException.

### Actual Behavior

We see NotSupportedException.

**Comment by Washi1337** [comment]
Should be fixed on latest commit on the `development` branch. Thanks for the catch!
