### ISSUE TITLE
The type or namespace name 'PE' does not exist in the namespace 'AsmResolver'

### ISSUE THREAD

**Issue by KulaGGin** [Washi1337/AsmResolver#88]
When I try to use AsmResolver(as described on the [basics](https://asmresolver.readthedocs.io/en/latest/pefile/basics.html) page) after I download the NuGet package, I get this error:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	CS0234	The type or namespace name 'PE' does not exist in the namespace 'AsmResolver' (are you missing an assembly reference?)	ConsoleApp2	D:\Projects\Tests\ConsoleApp2\ConsoleApp2\Program.cs	6	N/A
![devenv_3YgU4nivZL](https://user-images.githubusercontent.com/16989713/87959475-9ffbdd00-cabb-11ea-87ac-373d238b7814.png)

How to start using this library?

**Comment by Washi1337** [comment]
Make sure to enable showing pre-release versions. The nuget packages that you will need are version 4.0.0.beta.1

**Comment by KulaGGin** [comment]
Nothing changed after I uninstalled and installed 4.0.0.beta.1 version:
![devenv_VUIf0eQ2yl](https://user-images.githubusercontent.com/16989713/87960863-95424780-cabd-11ea-810a-4b8055efb34f.png)

**Comment by Washi1337** [comment]
AsmResolver switched from a single monolithic package to several smaller packages to allow users to only include the code that they need.

Every abstraction layer has its own package.
- `PEFile` will need `AsmResolver.PE.File`
- `PEImage` will need `AsmResolver.PE`
- `AssemblyDefinition` will need `AsmResolver.DotNet`.

Therefore, if you want to follow the tutorial you were referencing, you will need to also include the `AsmResolver.PE.File` package.

**Comment by KulaGGin** [comment]
Thank you, I missed that there are other NuGet packages other than just AsmResolver.
