### ISSUE TITLE
Incorrect Section FileOffset Calculation

### ISSUE THREAD

**Issue by SapientGuardian** [Washi1337/AsmResolver#95]
Hello! First I'd like to thank you for creating this library and others; they're more or less exactly what I need for a project I'm working on, and there is a serious lack of these sorts of projects written in C#.

I have a simple test in which I'm attempting to round-trip the attached EXE  (not malware; safe to execute and I can provide source if you want it), which is a very simple C++ program compiled with Visual Studio 2019 and not designed to be "tricky" in any way, through AsmResolver and verify that the resulting binary is identical:

```
            var originalBytes = Properties.Resources.NativeMemoryDemos;
            var peFile = PEFile.FromBytes(originalBytes);

            var msOutput = new MemoryStream();
            var output = new PEFile(peFile.DosHeader, peFile.FileHeader, peFile.OptionalHeader);
            foreach (var section in peFile.Sections)
            {
                var newSection = new PESection(section);
                output.Sections.Add(newSection);
            }
            output.Write(new BinaryStreamWriter(msOutput));
            Assert.Equal(originalBytes, msOutput.ToArray());
```

The output is identical, except for the FileOffset of the first section (`.textbss`), which has changed from 0 to 0x400, which is the same offset as the second section (`.text`) as illustrated in the screenshot from FileAlyzer below:

![image](https://user-images.githubusercontent.com/14796343/93686172-7ee74680-fa82-11ea-9631-44e1ae0fe18e.png)

I'm a novice when it comes to the PE format, so I apologize if I've incorrectly analyzed the problem, but I believe it to be the result of `AlignSections()` not taking into account the rule that "When a section contains only uninitialized data, this field should be zero." (https://docs.microsoft.com/en-us/windows/win32/debug/pe-format#section-table-section-headers). 

In `AlignSections()` it does this:
```
  var section = Sections[i];

                uint fileOffset = i > 0
                    ? Sections[i - 1].FileOffset + Sections[i - 1].GetPhysicalSize()
                    : OptionalHeader.SizeOfHeaders;
```

which forces the offset of the first section to 0x400, as that is the value of `OptionalHeader.SizeOfHeaders`.

I think the correct behavior would be to check if the section has the `ContentUninitializedData` flag set and force fileOffset to 0, regardless of whether it is the first section or not.

This brings up an interesting problem though, which is that in both the current and proposed behavior, I (the user) don't have a chance to write an arbitrary value into the table if I so desire.

If my analysis is correct, and you agree with my proposed solution (or have a different one), I'd love to submit a PR to fix it. Or even if you'd just like me to add the failing test case, I'd be happy to do that as well.

Thanks!

[NativeMemoryDemos.zip](https://github.com/Washi1337/AsmResolver/files/5250400/NativeMemoryDemos.zip)

**Comment by Washi1337** [comment]
Looks like I overlooked this small detail. Good catch!

I think however, from an API design standpoint, it is better to not use `ContentUninitializedData` as the deciding factor for emitting a 0 file offset and size. `PEFile` should be simple and as close as a 1:1 representation of the actual raw physical file. Technically, sections [i]can[/i] be flagged with the uninitialized data flag set, [i]and[/i] have physical data stored, regardless of whether it is valid or not.

Rather, I suggest we change the implementation of `VirtualSegment`, where we allow `PhysicalContents` to be set to `null`. If it is, we can return 0 for both the `FileOffset` property, as well as for the `GetPhysicalSize()`. I think that reduces the amount of logic to be added to `PEFile` a lot.

**Comment by SapientGuardian** [comment]
Agreed on not "trusting" the `ContentUninitializedData` flag and making decisions based on it. 

I've started down the path of making `PhysicalContents` nullable, but run into a couple problems.

The first, which was solved easily enough, was that if the first segment has no `PhysicalContents` (as is the case with my sample), the fileOffset starts at 0 instead of at `OptionalHeader.SizeOfHeaders` and corrupts the file. I addressed that like this:

```
 public void AlignSections()
        {
            PESection? lastPhysicalSectionWritten = null;

            for (int i = 0; i < Sections.Count; i++)
            {
                var section = Sections[i];

                uint fileOffset = lastPhysicalSectionWritten != null
                    ? lastPhysicalSectionWritten.FileOffset + lastPhysicalSectionWritten.GetPhysicalSize()
                    : OptionalHeader.SizeOfHeaders;
                uint rva = i > 0
                    ? Sections[i - 1].Rva + Sections[i - 1].GetVirtualSize()
                    : OptionalHeader.SizeOfHeaders.Align(OptionalHeader.SectionAlignment);

                section.UpdateOffsets(
                    fileOffset.Align(OptionalHeader.FileAlignment),
                    rva.Align(OptionalHeader.SectionAlignment));

                if (section.GetPhysicalSize() > 0)
                {
                    lastPhysicalSectionWritten = section;
                }
            }
        }
```

That seemed to have worked as intended, in that the second "real" section got the correct fileOffset, but the file was still corrupted, possibly because all of the RVAs were wrong.

I believe the problem is that the RVA is stored on the `PhysicalContents`, so if it is null, then there is nowhere for the data to be kept and this causes a cascading failure as subsequent segments rely on the one previous.

Should RVA belong to `VirtualSegment`, rather than `PhysicalContents`?

**Comment by Washi1337** [comment]
> Should RVA belong to VirtualSegment, rather than PhysicalContents?

Yes, this was indeed the idea I had in mind. We can just add an additional field to `VirtualSegment`, and update `Rva` and `UpdateOffsets` accordingly. 

Keep in mind though, that `UpdateOffsets` should update the offsets of `PhysicalContents` if it does exists. Various methods related to writing segments of data to the output stream rely on this.

Also try to avoid calling `GetPhysicalSize()` multiple times. It can be quite an expensive call to make if the segment is not just a normal data segment. Your current implementation calls it at least twice for each section.

**Comment by SapientGuardian** [comment]
Roger that. My test is passing now, along with all others. I've posted a PR for your consideration.
